Repository CloudNetService/CloudNet, pull requests merged in 2018-06, with the labels that each got.

#1 Fix API endpoint with uppercase letters
  cloudnet-core/src/main/java/de/dytanic/cloudnetcore/web/api/v1/WebsiteUtils.java
Labels: bug

#2 Befehl /reload wurde in der api geblockt
  cloudnet-api/cloudnet-api-bridge/src/main/java/de/dytanic/cloudnet/bridge/BukkitBootstrap.java
  cloudnet-api/cloudnet-api-bridge/src/main/java/de/dytanic/cloudnet/bridge/internal/listener/bukkit/ReloadListener.java
Labels: enhancement

#4 One pass packaging
  Jenkinsfile
  cloudnet-core/pom.xml
  cloudnet-core/src/main/resources/modules/CloudNet-Service-CloudFlareModule.jar
  cloudnet-core/src/main/resources/modules/CloudNet-Service-DevServiceModule.jar
  cloudnet-core/src/main/resources/modules/CloudNet-Service-MobModule.jar
  cloudnet-core/src/main/resources/modules/CloudNet-Service-NotifyServiceModule.jar
  cloudnet-core/src/main/resources/modules/CloudNet-Service-PermissionModule.jar
  cloudnet-core/src/main/resources/modules/CloudNet-Service-SignsModule.jar
  cloudnet-wrapper/pom.xml
  cloudnet-wrapper/src/main/resources/files/CloudNetAPI.jar
  pom.xml
Labels: enhancement

#5 Build Javadocs and remove examples from being built
  Jenkinsfile
  cloudnet-lib/pom.xml
  pom.xml
Labels: enhancement

#7 Add Method to get the registered player amount from the API
  cloudnet-api/cloudnet-api-core/src/main/java/de/dytanic/cloudnet/api/CloudAPI.java
  cloudnet-core/src/main/java/de/dytanic/cloudnetcore/network/NetworkManager.java
  cloudnet-lib/src/main/java/de/dytanic/cloudnet/lib/CloudNetwork.java
Labels: enhancement, good first issue
