Repository CloudNetService/CloudNet, pull requests merged in 2021-06, with the labels that each got.

#449 Better player handling
  cloudnet-driver/src/main/java/de/dytanic/cloudnet/driver/api/DriverAPIRequestType.java
  cloudnet-driver/src/main/java/de/dytanic/cloudnet/driver/database/Database.java
  cloudnet-driver/src/main/java/de/dytanic/cloudnet/driver/network/exception/SilentDecoderException.java
  cloudnet-driver/src/main/java/de/dytanic/cloudnet/driver/network/netty/NettyNetworkChannel.java
  cloudnet-driver/src/main/java/de/dytanic/cloudnet/driver/network/netty/NettyUtils.java
  cloudnet-driver/src/main/java/de/dytanic/cloudnet/driver/network/netty/codec/NettyPacketDecoder.java
  cloudnet-driver/src/main/java/de/dytanic/cloudnet/driver/network/netty/codec/NettyPacketEncoder.java
  cloudnet-driver/src/main/java/de/dytanic/cloudnet/driver/network/netty/codec/NettyPacketLengthDeserializer.java
  cloudnet-driver/src/main/java/de/dytanic/cloudnet/driver/network/netty/codec/NettyPacketLengthSerializer.java
  cloudnet-driver/src/main/java/de/dytanic/cloudnet/driver/network/netty/http/NettyWebSocketServerChannelHandler.java
  cloudnet-driver/src/main/java/de/dytanic/cloudnet/driver/permission/CachedPermissionManagement.java
  cloudnet-driver/src/main/java/de/dytanic/cloudnet/driver/permission/DefaultCachedPermissionManagement.java
  cloudnet-driver/src/main/java/de/dytanic/cloudnet/driver/permission/DefaultSynchronizedPermissionManagement.java
  cloudnet-driver/src/main/java/de/dytanic/cloudnet/driver/permission/IPermissionManagement.java
  cloudnet-driver/src/main/java/de/dytanic/cloudnet/driver/serialization/DefaultProtocolBuffer.java
  cloudnet-driver/src/test/java/de/dytanic/cloudnet/driver/network/netty/NettyHttpServerTest.java
  cloudnet-driver/src/test/java/de/dytanic/cloudnet/driver/network/netty/NettyUtilsTest.java
  cloudnet-driver/src/test/java/de/dytanic/cloudnet/driver/network/netty/codec/NettyPacketEncoderDecoderTest.java
  cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/BridgeConstants.java
  cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/BridgeHelper.java
  cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/bungee/BungeeCloudNetBridgePlugin.java
  cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/node/CloudNetBridgeModule.java
  cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/node/listener/BridgePlayerDisconnectListener.java
  cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/node/listener/NodeCustomChannelMessageListener.java
  cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/node/listener/PlayerManagerListener.java
  cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/node/player/NodePlayerManager.java
  cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/player/CloudPlayer.java
  cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/velocity/VelocityCloudNetBridgePlugin.java
  cloudnet-modules/cloudnet-cloudperms/src/main/java/de/dytanic/cloudnet/ext/cloudperms/CloudPermissionsHelper.java
  cloudnet-modules/cloudnet-cloudperms/src/main/java/de/dytanic/cloudnet/ext/cloudperms/CloudPermissionsManagement.java
  cloudnet-modules/cloudnet-cloudperms/src/main/java/de/dytanic/cloudnet/ext/cloudperms/bukkit/BukkitCloudNetCloudPermissionsPlugin.java
  cloudnet-modules/cloudnet-cloudperms/src/main/java/de/dytanic/cloudnet/ext/cloudperms/bukkit/BukkitPermissionInjectionHelper.java
  cloudnet-modules/cloudnet-cloudperms/src/main/java/de/dytanic/cloudnet/ext/cloudperms/bukkit/listener/BukkitCloudNetCloudPermissionsPlayerListener.java
  cloudnet-modules/cloudnet-cloudperms/src/main/java/de/dytanic/cloudnet/ext/cloudperms/bungee/BungeeCloudNetCloudPermissionsPlugin.java
  cloudnet-modules/cloudnet-cloudperms/src/main/java/de/dytanic/cloudnet/ext/cloudperms/bungee/listener/BungeeCloudNetCloudPermissionsPlayerListener.java
  cloudnet-modules/cloudnet-cloudperms/src/main/java/de/dytanic/cloudnet/ext/cloudperms/gomint/listener/GoMintCloudNetCloudPermissionsPlayerListener.java
  cloudnet-modules/cloudnet-cloudperms/src/main/java/de/dytanic/cloudnet/ext/cloudperms/nukkit/listener/NukkitCloudNetCloudPermissionsPlayerListener.java
  cloudnet-modules/cloudnet-cloudperms/src/main/java/de/dytanic/cloudnet/ext/cloudperms/velocity/VelocityCloudNetCloudPermissionsPermissionProvider.java
  cloudnet-modules/cloudnet-cloudperms/src/main/java/de/dytanic/cloudnet/ext/cloudperms/velocity/listener/VelocityCloudNetCloudPermissionsPlayerListener.java
  cloudnet-modules/cloudnet-database-mysql/src/main/java/de/dytanic/cloudnet/ext/database/mysql/MySQLDatabase.java
  cloudnet-modules/cloudnet-syncproxy/src/main/java/de/dytanic/cloudnet/ext/syncproxy/AbstractSyncProxyManagement.java
  cloudnet-modules/cloudnet-syncproxy/src/main/java/de/dytanic/cloudnet/ext/syncproxy/bungee/BungeeSyncProxyManagement.java
  cloudnet-modules/cloudnet-syncproxy/src/main/java/de/dytanic/cloudnet/ext/syncproxy/velocity/VelocitySyncProxyManagement.java
  cloudnet-wrapper-jvm/src/main/java/de/dytanic/cloudnet/wrapper/database/defaults/WrapperDatabase.java
  cloudnet-wrapper-jvm/src/main/java/de/dytanic/cloudnet/wrapper/permission/PermissionCacheListener.java
  cloudnet-wrapper-jvm/src/main/java/de/dytanic/cloudnet/wrapper/permission/WrapperPermissionManagement.java
  cloudnet/src/main/java/de/dytanic/cloudnet/database/h2/H2Database.java
  cloudnet/src/main/java/de/dytanic/cloudnet/database/sql/SQLDatabase.java
  cloudnet/src/main/java/de/dytanic/cloudnet/network/listener/cluster/PacketServerH2DatabaseListener.java
  cloudnet/src/main/java/de/dytanic/cloudnet/network/listener/cluster/PacketServerSetH2DatabaseDataListener.java
  cloudnet/src/main/java/de/dytanic/cloudnet/network/listener/cluster/PacketServerUpdatePermissionsListener.java
  cloudnet/src/main/java/de/dytanic/cloudnet/network/listener/driver/DriverPermissionManagementListener.java
  cloudnet/src/main/java/de/dytanic/cloudnet/permission/ClusterSynchronizedPermissionManagement.java
  cloudnet/src/main/java/de/dytanic/cloudnet/permission/DefaultDatabasePermissionManagement.java
Labels: target: release

#479 Delete a player from the database
  cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/BridgePlayerManager.java
  cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/event/BridgeDeleteCloudOfflinePlayerEvent.java
  cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/listener/BridgeCustomChannelMessageListener.java
  cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/node/command/CommandPlayers.java
  cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/node/listener/PlayerManagerListener.java
  cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/node/player/NodePlayerManager.java
  cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/player/IPlayerManager.java
  cloudnet/src/main/resources/lang/english.properties
  cloudnet/src/main/resources/lang/french.properties
  cloudnet/src/main/resources/lang/german.properties
Labels: target: release

#486 Revert change of sql syntax to insert or update
  cloudnet/src/main/java/de/dytanic/cloudnet/database/h2/H2Database.java
  cloudnet/src/main/java/de/dytanic/cloudnet/database/sql/SQLDatabase.java
Labels: priority: high, target: release

#488 Fix: Gson incompatibility on older server software implementations
  cloudnet-modules/cloudnet-signs/src/main/java/de/dytanic/cloudnet/ext/signs/SignConstants.java
Labels: priority: high, target: release

#490 1.17 caves & cliffs (part 1) support
  build.gradle
  cloudnet-modules/cloudnet-npcs/src/main/java/eu/cloudnetservice/cloudnet/ext/npcs/bukkit/BukkitNPCManagement.java
  cloudnet-modules/cloudnet-npcs/src/main/java/eu/cloudnetservice/cloudnet/ext/npcs/node/listener/IncludePluginListener.java
  cloudnet/src/main/resources/files/versions.json
Labels: target: 3.4

#491 Added time format into the CloudNet-Report module
  cloudnet-modules/cloudnet-report/src/main/java/de/dytanic/cloudnet/ext/report/CloudNetReportModule.java
  cloudnet-modules/cloudnet-report/src/main/java/de/dytanic/cloudnet/ext/report/listener/CloudNetReportListener.java
  cloudnet-modules/cloudnet-report/src/main/resources/module.json
Labels: target: 3.5

#499 RESTAPI - Permissions
  cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/node/CloudNetBridgeModule.java
  cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/node/http/v2/V2HttpHandlerBridge.java
  cloudnet-modules/cloudnet-rest/src/main/java/de/dytanic/cloudnet/ext/rest/CloudNetRestModule.java
  cloudnet-modules/cloudnet-rest/src/main/java/de/dytanic/cloudnet/ext/rest/v2/V2HttpHandlerPermission.java
  cloudnet-modules/cloudnet-rest/src/main/resources/openapi/v2-openapi.yml
Labels: status: accepted, target: 3.5

#496 SSH Key support for the SFTP TemplateStorage
  .idea/codeStyles/codeStyleConfig.xml
  cloudnet-modules/cloudnet-storage-ftp/src/main/java/de/dytanic/cloudnet/ext/storage/ftp/CloudNetStorageFTPModule.java
  cloudnet-modules/cloudnet-storage-ftp/src/main/java/de/dytanic/cloudnet/ext/storage/ftp/client/FTPCredentials.java
  cloudnet-modules/cloudnet-storage-ftp/src/main/java/de/dytanic/cloudnet/ext/storage/ftp/client/SFTPClient.java
  cloudnet-modules/cloudnet-storage-ftp/src/main/java/de/dytanic/cloudnet/ext/storage/ftp/storage/SFTPTemplateStorage.java
Labels: target: 3.5
