Repository CloudNetService/CloudNet, pull requests merged in 2022-01, with the labels that each got.

#577 docs: document all channel message classes
  .idea/inspectionProfiles/CloudNet.xml
  CONTRIBUTING.md
  driver/src/main/java/eu/cloudnetservice/cloudnet/driver/channel/ChannelMessage.java
  driver/src/main/java/eu/cloudnetservice/cloudnet/driver/channel/ChannelMessageSender.java
  driver/src/main/java/eu/cloudnetservice/cloudnet/driver/channel/ChannelMessageTarget.java
Labels: status: accepted, target: 4.0, documentation

#578 Add documentation to commands
  driver/src/main/java/eu/cloudnetservice/cloudnet/driver/command/CommandInfo.java
  node/src/main/java/eu/cloudnetservice/cloudnet/node/command/CommandProvider.java
  node/src/main/java/eu/cloudnetservice/cloudnet/node/command/annotation/CommandAlias.java
  node/src/main/java/eu/cloudnetservice/cloudnet/node/command/annotation/Description.java
  node/src/main/java/eu/cloudnetservice/cloudnet/node/command/defaults/DefaultCommandManager.java
  node/src/main/java/eu/cloudnetservice/cloudnet/node/command/defaults/DefaultCommandPostProcessor.java
  node/src/main/java/eu/cloudnetservice/cloudnet/node/command/defaults/DefaultCommandPreProcessor.java
  node/src/main/java/eu/cloudnetservice/cloudnet/node/command/defaults/DefaultCommandProvider.java
  node/src/main/java/eu/cloudnetservice/cloudnet/node/command/defaults/DefaultSuggestionProcessor.java
  node/src/main/java/eu/cloudnetservice/cloudnet/node/command/exception/ArgumentNotAvailableException.java
  node/src/main/java/eu/cloudnetservice/cloudnet/node/command/exception/CommandExceptionHandler.java
  node/src/main/java/eu/cloudnetservice/cloudnet/node/command/source/CommandSource.java
  node/src/main/java/eu/cloudnetservice/cloudnet/node/command/source/ConsoleCommandSource.java
  node/src/main/java/eu/cloudnetservice/cloudnet/node/command/source/DriverCommandSource.java
  node/src/main/java/eu/cloudnetservice/cloudnet/node/command/sub/CommandCluster.java
  node/src/main/java/eu/cloudnetservice/cloudnet/node/command/sub/CommandHelp.java
  node/src/main/java/eu/cloudnetservice/cloudnet/node/command/sub/CommandService.java
  node/src/main/java/eu/cloudnetservice/cloudnet/node/permission/command/PermissionUserCommandSource.java
Labels: status: accepted, target: 4.0, documentation

#589 Npcs/invisible name
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/NPC.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/command/NPCCommand.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/entity/BukkitPlatformSelectorEntity.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/entity/EntityBukkitPlatformSelectorEntity.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/entity/NPCBukkitPlatformSelector.java
Labels: enhancement, target: 4.0

#591 Remove unsafe socket address casts
  driver/src/main/java/eu/cloudnetservice/cloudnet/driver/network/HostAndPort.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/bukkit/BukkitBridgeManagement.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/bungeecord/BungeeCordBridgeManagement.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/bungeecord/BungeeCordPlayerManagementListener.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/nukkit/NukkitBridgeManagement.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/sponge/SpongeBridgeManagement.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/velocity/VelocityBridgeManagement.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/waterdog/WaterDogPEBridgeManagement.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/util/BridgeHostAndPortUtil.java
Labels: enhancement, target: 4.0

#590 Update rest api documentation page and schemas
  modules/rest/src/main/java/eu/cloudnetservice/modules/rest/v2/V2HttpHandlerNode.java
  modules/rest/src/main/resources/documentation/app.bundle.js
  modules/rest/src/main/resources/documentation/index.html
  modules/rest/src/main/resources/documentation/logo.svg
  modules/rest/src/main/resources/documentation/swagger.json
  modules/rest/src/main/resources/openapi/v1-openapi.yml
  modules/rest/src/main/resources/openapi/v2-openapi.yml
Labels: enhancement, target: 4.0, documentation

#594 Return a bad request response if a handler fails
  driver/src/main/java/eu/cloudnetservice/cloudnet/driver/network/netty/http/NettyHttpServerHandler.java
Labels: target: 4.0, fix

#592 Allow installable modules to specify a website
  build-extensions/src/main/kotlin/updater-extensions.kt
  node/src/main/java/eu/cloudnetservice/cloudnet/node/command/sub/CommandModules.java
  node/src/main/java/eu/cloudnetservice/cloudnet/node/module/ModuleEntry.java
Labels: enhancement, target: 4.0

#593 Fix double wrapped arguments passed to launcher patcher
  launcher/java17/src/main/java/eu/cloudnetservice/launcher/java17/updater/updaters/LauncherUpdater.java
Labels: target: 4.0, fix

#595 Make translation stuff easier to access for modules
  common/src/main/java/eu/cloudnetservice/cloudnet/common/language/I18n.java
  common/src/test/java/eu/cloudnetservice/cloudnet/common/language/I18nTest.java
  launcher/java17/src/main/resources/launcher.cnl
  node/src/main/java/eu/cloudnetservice/cloudnet/node/BootLogic.java
  node/src/main/java/eu/cloudnetservice/cloudnet/node/module/NodeModuleProviderHandler.java
  wrapper-jvm/src/main/java/eu/cloudnetservice/cloudnet/wrapper/Main.java
Labels: target: 4.0, improvement

#600 Add dependency checksum validation
  build-extensions/src/main/kotlin/Versions.kt
  build-extensions/src/main/kotlin/extensions.kt
  build-extensions/src/main/kotlin/updater-extensions.kt
  driver/build.gradle.kts
  driver/src/main/java/eu/cloudnetservice/cloudnet/driver/module/DefaultModuleDependencyLoader.java
  driver/src/main/java/eu/cloudnetservice/cloudnet/driver/module/ModuleDependency.java
  launcher/java17/src/main/java/eu/cloudnetservice/launcher/java17/dependency/Dependency.java
  launcher/java17/src/main/java/eu/cloudnetservice/launcher/java17/dependency/DependencyHelper.java
  launcher/java17/src/main/java/eu/cloudnetservice/launcher/java17/dependency/Repository.java
Labels: target: 4.0, improvement

#602 fix npc infoline duplications
  build.gradle
  cloudnet-modules/cloudnet-npcs/src/main/java/eu/cloudnetservice/cloudnet/ext/npcs/bukkit/BukkitCloudNetNPCPlugin.java
  cloudnet-modules/cloudnet-npcs/src/main/java/eu/cloudnetservice/cloudnet/ext/npcs/bukkit/BukkitNPCManagement.java
  cloudnet-modules/cloudnet-npcs/src/main/java/eu/cloudnetservice/cloudnet/ext/npcs/bukkit/listener/WorldEventListener.java
Labels: target: 3.4, fix

#603 Fix cluster disconnects and service starting
  cloudnet-driver/src/main/java/de/dytanic/cloudnet/driver/network/netty/NettyUtils.java
  cloudnet/src/main/java/de/dytanic/cloudnet/CloudNet.java
  cloudnet/src/main/java/de/dytanic/cloudnet/CloudNetTick.java
  cloudnet/src/main/java/de/dytanic/cloudnet/cluster/DefaultClusterNodeServerProvider.java
  cloudnet/src/main/java/de/dytanic/cloudnet/provider/service/NodeCloudServiceFactory.java
  cloudnet/src/main/java/de/dytanic/cloudnet/service/defaults/DefaultCloudServiceManager.java
Labels: target: 3.4, fix

#607 Heavily improve config loading and database handling
  driver/src/main/java/eu/cloudnetservice/cloudnet/driver/module/driver/DriverModule.java
  driver/src/main/java/eu/cloudnetservice/cloudnet/driver/module/driver/ModuleConfigurationInvalidException.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/node/CloudNetBridgeModule.java
  modules/cloudflare/src/main/java/eu/cloudnetservice/modules/cloudflare/CloudNetCloudflareModule.java
  modules/cloudflare/src/main/java/eu/cloudnetservice/modules/cloudflare/listener/CloudflareStartAndStopListener.java
  modules/cloudperms/src/main/java/eu/cloudnetservice/modules/cloudperms/node/CloudNetCloudPermissionsModule.java
  modules/cloudperms/src/main/java/eu/cloudnetservice/modules/cloudperms/node/config/CloudPermissionConfigHelper.java
  modules/database-mongodb/src/main/java/eu/cloudnetservice/modules/mongodb/CloudNetMongoDatabaseModule.java
  modules/database-mongodb/src/main/java/eu/cloudnetservice/modules/mongodb/MongoDBDatabaseProvider.java
  modules/database-mysql/src/main/java/eu/cloudnetservice/modules/mysql/CloudNetMySQLDatabaseModule.java
  modules/database-mysql/src/main/java/eu/cloudnetservice/modules/mysql/MySQLDatabase.java
  modules/database-mysql/src/main/java/eu/cloudnetservice/modules/mysql/MySQLDatabaseProvider.java
  modules/database-mysql/src/main/java/eu/cloudnetservice/modules/mysql/config/MySQLConfiguration.java
  modules/database-mysql/src/main/java/eu/cloudnetservice/modules/mysql/config/MySQLConnectionEndpoint.java
  modules/dockerized-services/src/main/java/eu/cloudnetservice/modules/docker/DockerizedServicesModule.java
  modules/labymod/src/main/java/eu/cloudnetservice/modules/labymod/node/CloudNetLabyModModule.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/node/CloudNetNPCModule.java
  modules/report/src/main/java/eu/cloudnetservice/modules/report/CloudNetReportModule.java
  modules/report/src/main/java/eu/cloudnetservice/modules/report/config/ReportConfigurationHelper.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/node/configuration/NodeSignsConfigurationHelper.java
  modules/storage-s3/src/main/java/eu/cloudnetservice/modules/s3/S3TemplateStorageModule.java
  modules/storage-sftp/src/main/java/eu/cloudnetservice/modules/sftp/SFTPTemplateStorageModule.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/node/CloudNetSyncProxyModule.java
  node/src/main/java/eu/cloudnetservice/cloudnet/node/database/AbstractDatabaseProvider.java
  node/src/main/java/eu/cloudnetservice/cloudnet/node/database/h2/H2Database.java
  node/src/main/java/eu/cloudnetservice/cloudnet/node/database/h2/H2DatabaseProvider.java
  node/src/main/java/eu/cloudnetservice/cloudnet/node/database/sql/SQLDatabase.java
  node/src/main/java/eu/cloudnetservice/cloudnet/node/database/sql/SQLDatabaseProvider.java
  node/src/main/java/eu/cloudnetservice/cloudnet/node/database/xodus/XodusDatabaseProvider.java
Labels: target: 4.0, improvement
