Repository CloudNetService/CloudNet, pull requests merged in 2022-10, with the labels that each got.

#882 chore: address recent service creation changes in the documentation
  driver/src/main/java/eu/cloudnetservice/driver/service/ServiceConfiguration.java
Labels: in: driver, t: documentation

#884 chore: create new release publishing workflows
  .github/workflows/gradle-release.yml
  .github/workflows/gradle.yml
  build-extensions/src/main/kotlin/publishing-extensions.kt
  build.gradle.kts
Labels: v: 4.X, t: ci

#872 chore: bump netty to 5.0.0.Alpha5
  gradle/libs.versions.toml
Labels: v: 4.X, t: dependencies

#873 [ci skip] chore: remove "dep" scope from renovate commit messages
  .github/renovate.json
Labels: v: 4.X

#869 fix: Add http:// to default influx module config
  modules/influx/src/main/java/eu/cloudnetservice/modules/influx/InfluxModule.java
Labels: v: 4.X, t: fix, in: module

#863 chore: Cleanup BungeeCordHelper by using reflexion
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/bungeecord/BungeeCordHelper.java
Labels: v: 4.X, t: improvement, in: module

#866 feat(node): add a command to rename groups easily
  node/src/main/java/eu/cloudnetservice/node/command/sub/GroupsCommand.java
  node/src/main/resources/lang/en_US.properties
Labels: v: 4.X, in: node, t: improvement

#881 fix: remove the process handle from the post process event
  modules/dockerized-services/src/main/java/eu/cloudnetservice/modules/docker/DockerizedService.java
  node/src/main/java/eu/cloudnetservice/node/event/service/CloudServicePostProcessStartEvent.java
  node/src/main/java/eu/cloudnetservice/node/service/defaults/JVMService.java
Labels: v: 4.X, in: node, t: fix, in: module

#890 fix: resolve some small issues in the current npc bukkit implementation
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/entity/BukkitPlatformSelectorEntity.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/listener/BukkitFunctionalityListener.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/listener/BukkitWorldListener.java
Labels: v: 4.X, t: fix, t: improvement, in: module

#879 feat: allow setting environment variables for services
  driver/src/main/java/eu/cloudnetservice/driver/service/GroupConfiguration.java
  driver/src/main/java/eu/cloudnetservice/driver/service/ProcessConfiguration.java
  driver/src/main/java/eu/cloudnetservice/driver/service/ServiceConfiguration.java
  driver/src/main/java/eu/cloudnetservice/driver/service/ServiceConfigurationBase.java
  driver/src/main/java/eu/cloudnetservice/driver/service/ServiceTask.java
  modules/dockerized-services/src/main/java/eu/cloudnetservice/modules/docker/DockerizedService.java
  node/src/main/java/eu/cloudnetservice/node/provider/NodeGroupConfigurationProvider.java
  node/src/main/java/eu/cloudnetservice/node/provider/NodeServiceTaskProvider.java
  node/src/main/java/eu/cloudnetservice/node/service/defaults/JVMService.java
  node/src/main/java/eu/cloudnetservice/node/service/defaults/NodeCloudServiceFactory.java
Labels: v: 4.X, in: node, in: driver, t: improvement

#865 feat(npcs): add a command to remove all spawned npcs
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/command/NPCCommand.java
Labels: v: 4.X, t: improvement, in: module

#883 chore: use var and new instanceof where possible
  common/src/main/java/eu/cloudnetservice/common/document/gson/JsonDocument.java
  common/src/main/java/eu/cloudnetservice/common/document/gson/RecordTypeAdapterFactory.java
  common/src/main/java/eu/cloudnetservice/common/io/ZipUtil.java
  common/src/main/java/eu/cloudnetservice/common/log/FallbackLoggerFactory.java
  driver/src/main/java/eu/cloudnetservice/driver/network/http/annotation/parser/HttpAnnotationProcessorUtil.java
  driver/src/main/java/eu/cloudnetservice/driver/network/netty/NettyUtil.java
  driver/src/main/java/eu/cloudnetservice/driver/network/netty/http/NettyHttpServerRequest.java
  driver/src/main/java/eu/cloudnetservice/driver/network/rpc/defaults/generation/ApiImplementationGenerator.java
  driver/src/main/java/eu/cloudnetservice/driver/network/rpc/defaults/generation/ChainedApiImplementationGenerator.java
  driver/src/main/java/eu/cloudnetservice/driver/network/rpc/defaults/rpc/DefaultRPCChain.java
  driver/src/test/java/eu/cloudnetservice/driver/network/netty/codec/VarIntCodecTest.java
  driver/src/test/java/eu/cloudnetservice/driver/network/rpc/handler/DefaultRPCHandlerTest.java
  ext/adventure-helper/src/main/java/eu/cloudnetservice/ext/component/ComponentConverter.java
  launcher/java17/src/main/java/eu/cloudnetservice/launcher/java17/dependency/Repository.java
  launcher/java17/src/main/java/eu/cloudnetservice/launcher/java17/util/Environment.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/node/CloudNetBridgeModule.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/bungeecord/BungeeCordDirectPlayerExecutor.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/bungeecord/BungeeCordPlayerManagementListener.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/bungeecord/command/BungeeCordHubCommand.java
  modules/database-mongodb/src/test/java/eu/cloudnetservice/modules/mongodb/MongoDBDatabaseTest.java
  modules/database-mysql/src/main/java/eu/cloudnetservice/modules/mysql/MySQLDatabaseProvider.java
  modules/database-mysql/src/test/java/eu/cloudnetservice/modules/mysql/MySQLDatabaseTest.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/command/NPCCommand.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/entity/BukkitPlatformSelectorEntity.java
  modules/report/src/main/java/eu/cloudnetservice/modules/report/emitter/ReportDataWriter.java
  modules/rest/src/main/java/eu/cloudnetservice/modules/rest/v2/V2HttpHandlerModule.java
  modules/rest/src/main/java/eu/cloudnetservice/modules/rest/v2/V2HttpHandlerTemplate.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/configuration/SignConfigurationEntry.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/util/LayoutUtil.java
  modules/storage-sftp/src/main/java/eu/cloudnetservice/modules/sftp/SFTPClientPool.java
  node/src/main/java/eu/cloudnetservice/node/Node.java
  node/src/main/java/eu/cloudnetservice/node/cluster/sync/JaversPrettyPrint.java
  node/src/main/java/eu/cloudnetservice/node/permission/DefaultDatabasePermissionManagement.java
  node/src/main/java/eu/cloudnetservice/node/service/defaults/config/BungeeConfigurationPreparer.java
  node/src/main/java/eu/cloudnetservice/node/version/execute/defaults/PaperApiVersionFetchStepExecutor.java
  node/src/test/java/eu/cloudnetservice/node/database/h2/H2DatabaseTest.java
  node/src/test/java/eu/cloudnetservice/node/database/xodus/XodusDatabaseTest.java
  wrapper-jvm/src/main/java/eu/cloudnetservice/wrapper/transform/bukkit/BukkitCommodoreTransformer.java
Labels: v: 4.X, t: improvement

#880 fix: the template installer now installs the templates correctly
  driver/src/main/java/eu/cloudnetservice/driver/provider/SpecificCloudServiceProvider.java
  modules/smart/src/main/java/eu/cloudnetservice/modules/smart/listener/CloudNetLocalServiceListener.java
  node/src/main/java/eu/cloudnetservice/node/command/sub/ServiceCommand.java
  node/src/main/java/eu/cloudnetservice/node/event/service/CloudServicePostPrepareEvent.java
  node/src/main/java/eu/cloudnetservice/node/event/service/CloudServicePrePrepareEvent.java
  node/src/main/java/eu/cloudnetservice/node/service/defaults/AbstractService.java
  node/src/main/java/eu/cloudnetservice/node/service/defaults/provider/EmptySpecificCloudServiceProvider.java
Labels: v: 4.X, in: node, in: driver, t: fix, t: improvement, in: module

#902 [ci skip] chore: lowercase "update" for renovate commits
  .github/renovate.json
Labels: v: 4.X

#901 chore: bump some dependencies which renovate isn't detecting
  build-extensions/src/main/kotlin/Versions.kt
  gradle/libs.versions.toml
Labels: v: 4.X, t: dependencies

#910 fix: resolve smart module regression causing invalid template inclusions
  driver/src/main/java/eu/cloudnetservice/driver/provider/SpecificCloudServiceProvider.java
  modules/smart/src/main/java/eu/cloudnetservice/modules/smart/listener/CloudNetLocalServiceListener.java
  node/src/main/java/eu/cloudnetservice/node/service/defaults/AbstractService.java
  node/src/main/java/eu/cloudnetservice/node/service/defaults/provider/EmptySpecificCloudServiceProvider.java
Labels: t: bug, p: high, v: 4.X, in: module

#909 fix: correctly set permissions for sponge system subject
  modules/cloudperms/src/main/java/eu/cloudnetservice/modules/cloudperms/sponge/service/CloudPermsPermissionService.java
  modules/cloudperms/src/main/java/eu/cloudnetservice/modules/cloudperms/sponge/service/memory/InMemorySubject.java
  modules/cloudperms/src/main/java/eu/cloudnetservice/modules/cloudperms/sponge/service/memory/InMemorySubjectCollection.java
  modules/cloudperms/src/main/java/eu/cloudnetservice/modules/cloudperms/sponge/service/system/SystemSubject.java
  modules/cloudperms/src/main/java/eu/cloudnetservice/modules/cloudperms/sponge/service/system/SystemSubjectCollection.java
Labels: v: 4.X, t: fix, in: module

#911 chore(sftp): don't ignore all exceptions when accessing the con. pool
  modules/storage-sftp/src/main/java/eu/cloudnetservice/modules/sftp/SFTPTemplateStorage.java
Labels: v: 4.X, t: improvement, in: module

#920 chore: ensure that we can read a VarInt when decoding the packet length
  driver/src/main/java/eu/cloudnetservice/driver/network/exception/SilentDecoderException.java
  driver/src/main/java/eu/cloudnetservice/driver/network/netty/NettyUtil.java
  driver/src/main/java/eu/cloudnetservice/driver/network/netty/codec/VarInt32FrameDecoder.java
Labels: v: 4.X, in: driver, t: fix, t: improvement

#921 fix: leave closing the buffer to netty when a channel becomes inactive
  driver/src/main/java/eu/cloudnetservice/driver/network/netty/codec/VarInt32FrameDecoder.java
Labels: v: 4.X, in: driver, t: fix

#918 fix: display the removed content when removing from a task collection
  modules/dockerized-services/src/main/java/eu/cloudnetservice/modules/docker/DockerCommand.java
  node/src/main/java/eu/cloudnetservice/node/command/sub/TasksCommand.java
Labels: v: 4.X, in: node, t: fix

#933 chore: bump mysql-connector to 8.0.31
  gradle/libs.versions.toml
Labels: v: 4.X, in: module, t: dependencies

#936 fix: correctly add the env variables property to groups
  common/src/main/java/eu/cloudnetservice/common/document/gson/JsonDocument.java
  node/src/main/java/eu/cloudnetservice/node/provider/NodeGroupConfigurationProvider.java
Labels: t: bug, v: 4.X, in: node

#943 build: reduce repo dependency resolution failures
  build-extensions/src/main/kotlin/extensions.kt
  build.gradle.kts
  modules/build.gradle.kts
Labels: v: 4.X, t: dependencies

#938 fix: npcs should hide ingame services but still update the online count
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/entity/BukkitPlatformSelectorEntity.java
Labels: v: 4.X, t: fix, in: module

#946 ci: bump pr-target-branch action to 2.1
  .github/workflows/prbranch.yml
Labels: v: 4.X, t: dependencies

#947 chore: increase default file chunk size to 50MB
  driver/src/main/java/eu/cloudnetservice/driver/network/chunk/defaults/builder/DefaultChunkedPacketSenderBuilder.java
Labels: v: 4.X, in: driver, t: improvement

#949 chore: improve cluster sync ux
  node/src/main/java/eu/cloudnetservice/node/Node.java
  node/src/main/java/eu/cloudnetservice/node/cluster/defaults/RemoteNodeServer.java
  node/src/main/java/eu/cloudnetservice/node/cluster/sync/DefaultDataSyncRegistry.java
  node/src/main/java/eu/cloudnetservice/node/network/listener/message/NodeChannelMessageListener.java
Labels: v: 4.X, in: node, t: improvement

#951 feat: npc show ingame services in the inventory
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/NPC.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/configuration/InventoryConfiguration.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/node/CloudNetNPCModule.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/command/NPCCommand.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/entity/BukkitPlatformSelectorEntity.java
Labels: v: 4.X, t: improvement, in: module

#952 fix: correctly fire root http handlers
  driver/src/main/java/eu/cloudnetservice/driver/network/netty/http/NettyHttpServerHandler.java
  driver/src/test/java/eu/cloudnetservice/driver/network/http/NettyHttpServerTest.java
Labels: v: 4.X, in: driver, t: fix
