Repository CloudNetService/CloudNet, pull requests merged in 2022-05, with the labels that each got.

#658 chore: cleanup and refactor sign code
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/AbstractSignManagement.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/SharedChannelMessageListener.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/Sign.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/configuration/SignLayoutsHolder.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/node/CloudNetSignsModule.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/node/NodeSignsListener.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/node/SignCommand.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/AbstractPlatformSignManagement.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/PlatformSign.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/PlatformSignManagement.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/SignsPlatformListener.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/bukkit/BukkitPlatformSign.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/bukkit/BukkitSignManagement.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/bukkit/BukkitSignsPlugin.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/bukkit/event/BukkitCloudSignInteractEvent.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/bukkit/functionality/SignInteractListener.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/bukkit/functionality/SignsCommand.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/nukkit/NukkitPlatformSign.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/nukkit/NukkitSignManagement.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/nukkit/NukkitSignsPlugin.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/nukkit/event/NukkitCloudSignInteractEvent.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/nukkit/functionality/SignInteractListener.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/nukkit/functionality/SignsCommand.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/sponge/SpongePlatformSign.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/sponge/SpongeSignManagement.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/sponge/SpongeSignsPlugin.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/sponge/event/SpongeCloudSignInteractEvent.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/sponge/functionality/SignInteractListener.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/sponge/functionality/SignsCommand.java
  modules/signs/src/main/resources/META-INF/sponge_plugins.json
  modules/signs/src/main/resources/plugin.glowstone.yml
  modules/signs/src/main/resources/plugin.minecraft_server.yml
  modules/signs/src/main/resources/plugin.nukkit.yml
  node/src/main/resources/files/versions.json
Labels: v: 4.X, t: improvement, in: module

#665 Bridge docs
  driver/src/main/java/eu/cloudnetservice/driver/service/property/ServiceProperty.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/BridgeManagement.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/BridgeServiceHelper.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/BridgeServiceProperties.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/WorldPosition.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/event/BridgeProxyPlayerServerSwitchEvent.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/node/command/PlayersCommand.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/node/player/NodePlayerExecutor.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/node/player/NodePlayerManager.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/PlatformBridgeManagement.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/bukkit/BukkitDirectPlayerExecutor.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/bungeecord/BungeeCordDirectPlayerExecutor.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/bungeecord/BungeeCordPlayerManagementListener.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/fabric/FabricDirectPlayerExecutor.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/nukkit/NukkitDirectPlayerExecutor.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/sponge/SpongeDirectPlayerExecutor.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/velocity/VelocityDirectPlayerExecutor.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/velocity/VelocityPlayerManagementListener.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/waterdog/WaterDogPEDirectPlayerExecutor.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/waterdog/WaterDogPEPlayerManagementListener.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/player/CloudOfflinePlayer.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/player/CloudPlayer.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/player/NetworkPlayerProxyInfo.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/player/NetworkPlayerServerInfo.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/player/NetworkServiceInfo.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/player/PlayerManager.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/player/PlayerProvider.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/player/ServicePlayer.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/player/executor/PlayerExecutor.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/player/executor/ServerSelectorType.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/rpc/ComponentObjectSerializer.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/rpc/TitleObjectSerializer.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/util/BridgeHostAndPortUtil.java
Labels: v: 4.X, t: documentation, in: module

#669 chore: pull latest crowdin translation changes
  node/src/main/resources/lang/de_DE.properties
Labels: t: translation, s: accepted

#668 Add inclusions to deployments
  common/src/main/java/eu/cloudnetservice/common/WildcardUtil.java
  common/src/main/java/eu/cloudnetservice/common/document/gson/JsonDocument.java
  common/src/main/java/eu/cloudnetservice/common/document/gson/PatternTypeAdapter.java
  common/src/test/java/eu/cloudnetservice/common/WildcardUtilTest.java
  driver/src/main/java/eu/cloudnetservice/driver/network/rpc/defaults/object/DefaultObjectMapper.java
  driver/src/main/java/eu/cloudnetservice/driver/network/rpc/defaults/object/serializers/PatternObjectSerializer.java
  driver/src/main/java/eu/cloudnetservice/driver/service/ServiceDeployment.java
  node/src/main/java/eu/cloudnetservice/node/command/sub/GroupsCommand.java
  node/src/main/java/eu/cloudnetservice/node/command/sub/ServiceCommand.java
  node/src/main/java/eu/cloudnetservice/node/command/sub/TasksCommand.java
  node/src/main/java/eu/cloudnetservice/node/service/defaults/AbstractService.java
Labels: t: feature request, v: 4.X, in: node, in: driver
