Repository CloudNetService/CloudNet, pull requests merged in 2022-12, with the labels that each got.

#988 feat: add injection layer to every platform
  driver/src/main/java/eu/cloudnetservice/driver/inject/InjectUtil.java
  driver/src/main/java/eu/cloudnetservice/driver/inject/InjectionLayer.java
  driver/src/main/java/eu/cloudnetservice/driver/inject/InjectionLayerProvider.java
  ext/platform-layer/build.gradle.kts
  ext/platform-layer/src/main/java/eu/cloudnetservice/ext/platformlayer/BukkitLayer.java
  ext/platform-layer/src/main/java/eu/cloudnetservice/ext/platformlayer/BungeeCordLayer.java
  ext/platform-layer/src/main/java/eu/cloudnetservice/ext/platformlayer/FabricLayer.java
  ext/platform-layer/src/main/java/eu/cloudnetservice/ext/platformlayer/MinestomLayer.java
  ext/platform-layer/src/main/java/eu/cloudnetservice/ext/platformlayer/NukkitLayer.java
  ext/platform-layer/src/main/java/eu/cloudnetservice/ext/platformlayer/SpongeLayer.java
  ext/platform-layer/src/main/java/eu/cloudnetservice/ext/platformlayer/VelocityLayer.java
  ext/platform-layer/src/main/java/eu/cloudnetservice/ext/platformlayer/WaterDogPELayer.java
  settings.gradle.kts
Labels: v: 4.X

#992 chore: remove instance methods and old getters / setters
  driver/src/main/java/eu/cloudnetservice/driver/CloudNetDriver.java
  driver/src/main/java/eu/cloudnetservice/driver/event/events/permission/PermissionServiceSetEvent.java
  driver/src/main/java/eu/cloudnetservice/driver/module/driver/DriverModule.java
  driver/src/main/java/eu/cloudnetservice/driver/network/rpc/RPCHandler.java
  driver/src/main/java/eu/cloudnetservice/driver/network/rpc/defaults/handler/DefaultRPCHandler.java
  driver/src/main/java/eu/cloudnetservice/driver/permission/DefaultPermissionManagement.java
  driver/src/main/java/eu/cloudnetservice/driver/permission/PermissionManagement.java
  node/src/main/java/eu/cloudnetservice/node/Node.java
  node/src/main/java/eu/cloudnetservice/node/ShutdownHandler.java
  node/src/main/java/eu/cloudnetservice/node/TickLoop.java
  node/src/main/java/eu/cloudnetservice/node/command/sub/ConfigCommand.java
  node/src/main/java/eu/cloudnetservice/node/config/JsonConfiguration.java
  node/src/main/java/eu/cloudnetservice/node/http/V2HttpHandler.java
  wrapper-jvm/src/main/java/eu/cloudnetservice/wrapper/ShutdownHandler.java
  wrapper-jvm/src/main/java/eu/cloudnetservice/wrapper/Wrapper.java
  wrapper-jvm/src/main/java/eu/cloudnetservice/wrapper/permission/WrapperPermissionManagement.java
Labels: v: 4.X, in: node, in: driver, in: wrapper

#993 chore: migrate papi expansion to use injection
  plugins/papi-expansion/src/main/java/eu/cloudnetservice/plugins/papi/CloudNetPapiExpansion.java
Labels: v: 4.X, in: plugin

#991 chore: migrate cloudflare module to use dependency injection
  modules/cloudflare/src/main/java/eu/cloudnetservice/modules/cloudflare/CloudNetCloudflareModule.java
  modules/cloudflare/src/main/java/eu/cloudnetservice/modules/cloudflare/cloudflare/CloudFlareRecordManager.java
  modules/cloudflare/src/main/java/eu/cloudnetservice/modules/cloudflare/listener/CloudflareServiceStateListener.java
Labels: v: 4.X, in: module

#998 chore: add fabric info generation & fix template file loading
  ext/platform-inject-support/src/main/java/eu/cloudnetservice/ext/platforminject/info/NightConfigInfoGenerator.java
  ext/platform-inject-support/src/main/java/eu/cloudnetservice/ext/platforminject/platform/fabric/FabricMainClassGenerator.java
  ext/platform-inject-support/src/main/java/eu/cloudnetservice/ext/platforminject/platform/fabric/FabricPlatformInfoProvider.java
  ext/platform-inject-support/src/main/java/eu/cloudnetservice/ext/platforminject/platform/fabric/FabricPluginInfoGenerator.java
  ext/platform-inject-support/src/main/java/eu/cloudnetservice/ext/platforminject/provider/UnsupportedGenerationInfoProvider.java
  ext/platform-inject-support/src/main/java/eu/cloudnetservice/ext/platforminject/util/ResourceUtil.java
Labels: v: 4.X, t: fix, t: improvement, in: ext

#997 chore: add registry for injection layers
  driver/src/main/java/eu/cloudnetservice/driver/inject/DefaultInjectionLayer.java
  driver/src/main/java/eu/cloudnetservice/driver/inject/InjectionLayer.java
  driver/src/main/java/eu/cloudnetservice/driver/inject/InjectionLayerProvider.java
  driver/src/main/java/eu/cloudnetservice/driver/inject/InjectionLayerRegistry.java
  driver/src/main/java/eu/cloudnetservice/driver/inject/UncloseableInjectionLayer.java
  ext/platform-inject-support/src/main/java/eu/cloudnetservice/ext/platforminject/defaults/BasePlatformPluginManager.java
  ext/platform-inject-support/src/main/java/eu/cloudnetservice/ext/platforminject/platform/bukkit/BukkitPlatformPluginManager.java
  ext/platform-inject-support/src/main/java/eu/cloudnetservice/ext/platforminject/platform/bungeecord/BungeeCordPlatformPluginManager.java
  ext/platform-inject-support/src/main/java/eu/cloudnetservice/ext/platforminject/platform/fabric/FabricPlatformPluginManager.java
  ext/platform-inject-support/src/main/java/eu/cloudnetservice/ext/platforminject/platform/minestom/MinestomPlatformPluginManager.java
  ext/platform-inject-support/src/main/java/eu/cloudnetservice/ext/platforminject/platform/nukkit/NukkitPlatformPluginManager.java
  ext/platform-inject-support/src/main/java/eu/cloudnetservice/ext/platforminject/platform/sponge/SpongePlatformPluginManager.java
  ext/platform-inject-support/src/main/java/eu/cloudnetservice/ext/platforminject/platform/velocity/VelocityPlatformPluginManager.java
  ext/platform-inject-support/src/main/java/eu/cloudnetservice/ext/platforminject/platform/waterdog/WaterDogPlatformPluginManager.java
  ext/platform-inject-support/src/main/java/eu/cloudnetservice/ext/platforminject/provider/BasePlatformInfoProvider.java
  ext/platform-inject-support/src/main/java/eu/cloudnetservice/ext/platforminject/util/FunctionalUtil.java
Labels: v: 4.X, in: driver, t: improvement

#999 chore: bind injection layers to more generic types
  driver/build.gradle.kts
  driver/src/main/java/eu/cloudnetservice/driver/inject/InjectionLayer.java
  driver/src/main/java/eu/cloudnetservice/driver/inject/InjectionLayerProvider.java
  gradle/libs.versions.toml
Labels: v: 4.X, in: driver, t: improvement

#1000 chore: migrate some smaller modules to use dependency injection
  modules/cloudflare/src/main/java/eu/cloudnetservice/modules/cloudflare/CloudNetCloudflareModule.java
  modules/database-mongodb/src/main/java/eu/cloudnetservice/modules/mongodb/CloudNetMongoDatabaseModule.java
  modules/database-mysql/src/main/java/eu/cloudnetservice/modules/mysql/CloudNetMySQLDatabaseModule.java
  modules/dockerized-services/src/main/java/eu/cloudnetservice/modules/docker/DockerCommand.java
  modules/dockerized-services/src/main/java/eu/cloudnetservice/modules/docker/DockerizedServicesModule.java
  modules/influx/src/main/java/eu/cloudnetservice/modules/influx/InfluxModule.java
  modules/influx/src/main/java/eu/cloudnetservice/modules/influx/publish/PublisherRegistry.java
  modules/influx/src/main/java/eu/cloudnetservice/modules/influx/publish/defaults/DefaultPublisherRegistry.java
  modules/influx/src/main/java/eu/cloudnetservice/modules/influx/publish/publishers/ConnectedNodeInfoPublisher.java
  modules/influx/src/main/java/eu/cloudnetservice/modules/influx/publish/publishers/RunningServiceProcessSnapshotPublisher.java
  modules/report/src/main/java/eu/cloudnetservice/modules/report/CloudNetReportModule.java
  modules/report/src/main/java/eu/cloudnetservice/modules/report/emitter/EmitterRegistry.java
  modules/report/src/main/java/eu/cloudnetservice/modules/report/emitter/defaults/GroupConfigDataEmitter.java
  modules/report/src/main/java/eu/cloudnetservice/modules/report/emitter/defaults/HeapDumpDataEmitter.java
  modules/report/src/main/java/eu/cloudnetservice/modules/report/emitter/defaults/LocalModuleDataEmitter.java
  modules/report/src/main/java/eu/cloudnetservice/modules/report/emitter/defaults/LocalNodeConfigDataEmitter.java
  modules/report/src/main/java/eu/cloudnetservice/modules/report/emitter/defaults/NodeServerDataEmitter.java
  modules/report/src/main/java/eu/cloudnetservice/modules/report/emitter/defaults/ServiceInfoDataEmitter.java
  modules/report/src/main/java/eu/cloudnetservice/modules/report/emitter/defaults/ServiceTasksDataEmitter.java
  modules/report/src/main/java/eu/cloudnetservice/modules/report/emitter/defaults/SystemInfoDataEmitter.java
  modules/report/src/main/java/eu/cloudnetservice/modules/report/emitter/defaults/ThreadInfoDataEmitter.java
Labels: v: 4.X, t: fix, in: module

#1001 chore: migrate the smart module to use dependency injection
  modules/smart/src/main/java/eu/cloudnetservice/modules/smart/CloudNetSmartModule.java
  modules/smart/src/main/java/eu/cloudnetservice/modules/smart/SmartCommand.java
  modules/smart/src/main/java/eu/cloudnetservice/modules/smart/listener/CloudNetLocalServiceListener.java
  modules/smart/src/main/java/eu/cloudnetservice/modules/smart/listener/CloudNetLocalServiceTaskListener.java
  modules/smart/src/main/java/eu/cloudnetservice/modules/smart/listener/CloudNetTickListener.java
Labels: v: 4.X, t: improvement, in: module

#1004 chore: allow a plugin info generator to create multiple files
  ext/platform-inject-support/src/main/java/eu/cloudnetservice/ext/platforminject/info/NightConfigInfoGenerator.java
  ext/platform-inject-support/src/main/java/eu/cloudnetservice/ext/platforminject/platform/bukkit/BukkitPluginInfoGenerator.java
Labels: v: 4.X, t: improvement, in: ext

#1005 chore: migrate npc module to use dependency injection
  modules/build.gradle.kts
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/AbstractNPCManagement.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/NPCManagement.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/node/CloudNetNPCModule.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/node/NPCCommand.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/node/NodeNPCManagement.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/PlatformNPCManagement.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/BukkitNPCPlugin.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/BukkitPlatformNPCManagement.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/command/NPCCommand.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/listener/BukkitEntityProtectionListener.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/listener/BukkitFunctionalityListener.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/listener/BukkitWorldListener.java
  modules/npcs/src/main/resources/plugin.minecraft_server.yml
Labels: v: 4.X, t: improvement, in: module

#1007 chore: add missing DI annotations to the docker service factory
  modules/dockerized-services/src/main/java/eu/cloudnetservice/modules/docker/DockerizedLocalCloudServiceFactory.java
Labels: v: 4.X, t: fix, in: module

#1009 chore: migrate rest module to use dependency injection
  driver/src/main/java/eu/cloudnetservice/driver/network/http/annotation/parser/DefaultHttpAnnotationParser.java
  driver/src/main/java/eu/cloudnetservice/driver/network/http/annotation/parser/HttpAnnotationParser.java
  modules/rest/src/main/java/eu/cloudnetservice/modules/rest/CloudNetRestModule.java
  modules/rest/src/main/java/eu/cloudnetservice/modules/rest/v2/V2HttpHandlerAuthorization.java
  modules/rest/src/main/java/eu/cloudnetservice/modules/rest/v2/V2HttpHandlerCluster.java
  modules/rest/src/main/java/eu/cloudnetservice/modules/rest/v2/V2HttpHandlerDatabase.java
  modules/rest/src/main/java/eu/cloudnetservice/modules/rest/v2/V2HttpHandlerDocumentation.java
  modules/rest/src/main/java/eu/cloudnetservice/modules/rest/v2/V2HttpHandlerGroup.java
  modules/rest/src/main/java/eu/cloudnetservice/modules/rest/v2/V2HttpHandlerModule.java
  modules/rest/src/main/java/eu/cloudnetservice/modules/rest/v2/V2HttpHandlerNode.java
  modules/rest/src/main/java/eu/cloudnetservice/modules/rest/v2/V2HttpHandlerPermission.java
  modules/rest/src/main/java/eu/cloudnetservice/modules/rest/v2/V2HttpHandlerService.java
  modules/rest/src/main/java/eu/cloudnetservice/modules/rest/v2/V2HttpHandlerServiceVersionProvider.java
  modules/rest/src/main/java/eu/cloudnetservice/modules/rest/v2/V2HttpHandlerSession.java
  modules/rest/src/main/java/eu/cloudnetservice/modules/rest/v2/V2HttpHandlerTask.java
  modules/rest/src/main/java/eu/cloudnetservice/modules/rest/v2/V2HttpHandlerTemplate.java
  modules/rest/src/main/java/eu/cloudnetservice/modules/rest/v2/V2HttpHandlerTemplateStorage.java
Labels: v: 4.X, t: improvement, in: module

#1008 chore: migrate storage modules to use dependency injection
  modules/storage-s3/src/main/java/eu/cloudnetservice/modules/s3/S3TemplateStorageModule.java
  modules/storage-sftp/src/main/java/eu/cloudnetservice/modules/sftp/SFTPTemplateStorageModule.java
Labels: v: 4.X, t: improvement, in: module

#964 feat: improve formatting for motds and placeholders in the player info
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/config/SyncProxyConfiguration.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/config/SyncProxyMotd.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/platform/bungee/BungeeCordSyncProxyListener.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/platform/bungee/BungeeCordSyncProxyManagement.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/platform/velocity/VelocitySyncProxyListener.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/platform/waterdog/WaterDogPESyncProxyListener.java
Labels: v: 4.X, t: fix, t: improvement, in: module

#1006 chore: migrate the labymod module to DI
  modules/labymod/build.gradle.kts
  modules/labymod/src/main/java/eu/cloudnetservice/modules/labymod/node/CloudNetLabyModModule.java
  modules/labymod/src/main/java/eu/cloudnetservice/modules/labymod/node/NodeLabyModListener.java
  modules/labymod/src/main/java/eu/cloudnetservice/modules/labymod/node/NodeLabyModManagement.java
  modules/labymod/src/main/java/eu/cloudnetservice/modules/labymod/platform/PlatformLabyModListener.java
  modules/labymod/src/main/java/eu/cloudnetservice/modules/labymod/platform/PlatformLabyModManagement.java
  modules/labymod/src/main/java/eu/cloudnetservice/modules/labymod/platform/bungeecord/BungeeCordLabyModListener.java
  modules/labymod/src/main/java/eu/cloudnetservice/modules/labymod/platform/bungeecord/BungeeCordLabyModPlugin.java
  modules/labymod/src/main/java/eu/cloudnetservice/modules/labymod/platform/velocity/VelocityLabyModListener.java
  modules/labymod/src/main/java/eu/cloudnetservice/modules/labymod/platform/velocity/VelocityLabyModPlugin.java
  modules/labymod/src/main/resources/bungee.yml
Labels: v: 4.X, t: improvement, in: plugin, in: module

#1010 chore: migrate plugins to dependency injection
  ext/platform-inject-support/src/main/java/eu/cloudnetservice/ext/platforminject/platform/bukkit/BukkitPlatformPluginManager.java
  ext/platform-inject-support/src/main/java/eu/cloudnetservice/ext/platforminject/platform/minestom/MinestomPlatformPluginManager.java
  plugins/build.gradle.kts
  plugins/chat/src/main/java/eu/cloudnetservice/plugins/chat/BukkitChatPlugin.java
  plugins/chat/src/main/java/eu/cloudnetservice/plugins/chat/ChatFormatter.java
  plugins/chat/src/main/java/eu/cloudnetservice/plugins/chat/MinestomChatExtension.java
  plugins/chat/src/main/java/eu/cloudnetservice/plugins/chat/NukkitChatPlugin.java
  plugins/chat/src/main/java/eu/cloudnetservice/plugins/chat/SpongeChatPlugin.java
  plugins/chat/src/main/resources/META-INF/sponge_plugins.json
  plugins/chat/src/main/resources/extension.json
  plugins/chat/src/main/resources/nukkit.yml
  plugins/chat/src/main/resources/plugin.yml
  plugins/simplenametags/src/main/java/eu/cloudnetservice/plugins/simplenametags/CloudSimpleNameTagsListener.java
  plugins/simplenametags/src/main/java/eu/cloudnetservice/plugins/simplenametags/SimpleNameTagsManager.java
  plugins/simplenametags/src/main/java/eu/cloudnetservice/plugins/simplenametags/bukkit/BukkitSimpleNameTagsManager.java
  plugins/simplenametags/src/main/java/eu/cloudnetservice/plugins/simplenametags/bukkit/BukkitSimpleNameTagsPlugin.java
  plugins/simplenametags/src/main/java/eu/cloudnetservice/plugins/simplenametags/minestom/MinestomSimpleNameTagsExtension.java
  plugins/simplenametags/src/main/java/eu/cloudnetservice/plugins/simplenametags/minestom/MinestomSimpleNameTagsManager.java
  plugins/simplenametags/src/main/java/eu/cloudnetservice/plugins/simplenametags/sponge/SpongeSimpleNameTagsManager.java
  plugins/simplenametags/src/main/java/eu/cloudnetservice/plugins/simplenametags/sponge/SpongeSimpleNameTagsPlugin.java
  plugins/simplenametags/src/main/resources/META-INF/sponge_plugins.json
  plugins/simplenametags/src/main/resources/extension.json
  plugins/simplenametags/src/main/resources/plugin.yml
Labels: v: 4.X, t: improvement, in: module

#1011 chore: migrate the syncproxy module to use DI
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/bungeecord/PendingConnectionProxiedPlayer.java
  modules/syncproxy/build.gradle.kts
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/SyncProxyManagement.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/config/SyncProxyConfiguration.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/config/SyncProxyMotd.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/config/SyncProxyTabList.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/node/CloudNetSyncProxyModule.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/node/NodeSyncProxyManagement.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/node/command/SyncProxyCommand.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/node/listener/NodeSyncProxyChannelMessageListener.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/platform/PlatformSyncProxyManagement.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/platform/bungee/BungeeCordSyncProxyListener.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/platform/bungee/BungeeCordSyncProxyManagement.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/platform/bungee/BungeeCordSyncProxyPlugin.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/platform/listener/SyncProxyCloudListener.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/platform/velocity/VelocitySyncProxyListener.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/platform/velocity/VelocitySyncProxyManagement.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/platform/velocity/VelocitySyncProxyPlugin.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/platform/waterdog/WaterDogPESyncProxyListener.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/platform/waterdog/WaterDogPESyncProxyManagement.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/platform/waterdog/WaterDogPESyncProxyPlugin.java
  modules/syncproxy/src/main/resources/plugin.bungeecord.yml
  modules/syncproxy/src/main/resources/plugin.waterdog_pe.yml
Labels: v: 4.X, t: improvement, in: module

#1012 chore: some small cleanups for injection
  modules/labymod/src/main/java/eu/cloudnetservice/modules/labymod/node/CloudNetLabyModModule.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/node/CloudNetNPCModule.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/node/NPCCommand.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/node/NodeNPCManagement.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/node/listeners/NodeSetupListener.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/BukkitNPCPlugin.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/BukkitPlatformNPCManagement.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/command/NPCCommand.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/entity/BukkitPlatformSelectorEntity.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/entity/EntityBukkitPlatformSelectorEntity.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/entity/NPCBukkitPlatformSelector.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/listener/BukkitFunctionalityListener.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/listener/BukkitWorldListener.java
  node/src/main/java/eu/cloudnetservice/node/cluster/defaults/DefaultNodeServerProvider.java
  node/src/main/java/eu/cloudnetservice/node/module/listener/PluginIncludeListener.java
Labels: v: 4.X

#1015 chore: migrate the signs module to use DI
  modules/signs/build.gradle.kts
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/AbstractSignManagement.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/SharedChannelMessageListener.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/SignManagement.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/node/CloudNetSignsModule.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/node/NodeSignManagement.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/node/NodeSignsListener.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/node/SignCommand.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/node/util/SignEntryTaskSetup.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/PlatformSignManagement.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/SignsPlatformListener.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/bukkit/BukkitPlatformSign.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/bukkit/BukkitSignManagement.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/bukkit/BukkitSignsPlugin.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/bukkit/functionality/SignInteractListener.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/bukkit/functionality/SignsCommand.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/minestom/MinestomPlatformSign.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/minestom/MinestomSignManagement.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/minestom/MinestomSignsExtension.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/minestom/functionality/SignInteractListener.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/minestom/functionality/SignsCommand.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/nukkit/NukkitPlatformSign.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/nukkit/NukkitSignManagement.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/nukkit/NukkitSignsPlugin.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/nukkit/functionality/SignInteractListener.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/nukkit/functionality/SignsCommand.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/sponge/SpongePlatformSign.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/sponge/SpongeSignManagement.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/sponge/SpongeSignsPlugin.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/sponge/functionality/CommandRegistrationListener.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/sponge/functionality/SignInteractListener.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/sponge/functionality/SignsCommand.java
  modules/signs/src/main/resources/extension.json
  modules/signs/src/main/resources/plugin.glowstone.yml
  modules/signs/src/main/resources/plugin.minecraft_server.yml
  modules/signs/src/main/resources/plugin.nukkit.yml
  settings.gradle.kts
Labels: v: 4.X, t: improvement, in: module

#1034 fix: test all modules & plugins on all supported platforms
  .idea/codeStyles/Project.xml
  driver/src/main/java/eu/cloudnetservice/driver/inject/DefaultInjectionLayer.java
  ext/platform-inject-support/api/src/main/java/eu/cloudnetservice/ext/platforminject/api/data/ParsedPluginData.java
  ext/platform-inject-support/api/src/main/java/eu/cloudnetservice/ext/platforminject/api/data/PluginDataParser.java
  ext/platform-inject-support/api/src/main/java/eu/cloudnetservice/ext/platforminject/api/stereotype/PlatformPlugin.java
  ext/platform-inject-support/processor/src/main/java/eu/cloudnetservice/ext/platforminject/processor/infogen/NightConfigInfoGenerator.java
  ext/platform-inject-support/processor/src/main/java/eu/cloudnetservice/ext/platforminject/processor/platform/bukkit/BukkitPluginInfoGenerator.java
  ext/platform-inject-support/processor/src/main/java/eu/cloudnetservice/ext/platforminject/processor/platform/minestom/MinestomPluginInfoGenerator.java
  ext/platform-inject-support/processor/src/main/java/eu/cloudnetservice/ext/platforminject/processor/platform/nukkit/NukkitPluginInfoGenerator.java
  ext/platform-inject-support/processor/src/main/java/eu/cloudnetservice/ext/platforminject/processor/platform/sponge/SpongePluginInfoGenerator.java
  ext/platform-inject-support/runtime/src/main/java/eu/cloudnetservice/ext/platforminject/runtime/platform/minestom/MinestomPlatformPluginManager.java
  gradle/libs.versions.toml
  modules/bridge/build.gradle.kts
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/node/CloudNetBridgeModule.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/node/player/NodePlayerManager.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/minestom/MinestomBridgeExtension.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/sponge/SpongeBridgePlugin.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/sponge/SpongePlayerManagementListener.java
  modules/bridge/src/main/resources/META-INF/sponge_plugins.json
  modules/bridge/src/main/resources/META-INF/sponge_plugins.json.template
  modules/build.gradle.kts
  modules/cloudperms/build.gradle.kts
  modules/cloudperms/src/main/java/eu/cloudnetservice/modules/cloudperms/sponge/SpongeCloudPermissionsPlugin.java
  modules/cloudperms/src/main/java/eu/cloudnetservice/modules/cloudperms/velocity/VelocityCloudPermissionProvider.java
  modules/dockerized-services/src/main/java/eu/cloudnetservice/modules/docker/DockerizedLocalCloudServiceFactory.java
  modules/labymod/build.gradle.kts
  modules/labymod/src/main/java/eu/cloudnetservice/modules/labymod/node/CloudNetLabyModModule.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/node/CloudNetSignsModule.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/node/NodeSignManagement.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/bukkit/BukkitSignManagement.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/bukkit/functionality/SignInteractListener.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/minestom/MinestomSignManagement.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/minestom/MinestomSignsExtension.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/minestom/event/MinestomCloudSignInteractEvent.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/nukkit/NukkitSignManagement.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/sponge/CommandRegistrationListener.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/sponge/SpongeSignManagement.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/sponge/SpongeSignsPlugin.java
  modules/signs/src/main/resources/META-INF/sponge_plugins.json
  modules/signs/src/main/resources/META-INF/sponge_plugins.json.template
  modules/syncproxy/build.gradle.kts
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/node/CloudNetSyncProxyModule.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/platform/bungee/BungeeCordSyncProxyManagement.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/platform/bungee/BungeeCordSyncProxyPlugin.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/platform/waterdog/WaterDogPESyncProxyManagement.java
  node/src/main/java/eu/cloudnetservice/node/ShutdownHandler.java
  node/src/main/java/eu/cloudnetservice/node/cluster/defaults/DefaultLocalNodeServer.java
  node/src/main/java/eu/cloudnetservice/node/cluster/defaults/DefaultNodeServerProvider.java
  node/src/main/java/eu/cloudnetservice/node/command/sub/ExitCommand.java
  node/src/main/java/eu/cloudnetservice/node/command/sub/TasksCommand.java
  node/src/main/java/eu/cloudnetservice/node/setup/SpecificTaskSetup.java
  plugins/build.gradle.kts
  plugins/chat/src/main/java/eu/cloudnetservice/plugins/chat/BukkitChatPlugin.java
  plugins/chat/src/main/java/eu/cloudnetservice/plugins/chat/MinestomChatExtension.java
  plugins/chat/src/main/java/eu/cloudnetservice/plugins/chat/SpongeChatPlugin.java
  plugins/papi-expansion/build.gradle.kts
  plugins/simplenametags/src/main/java/eu/cloudnetservice/plugins/simplenametags/bukkit/BukkitSimpleNameTagsPlugin.java
  plugins/simplenametags/src/main/java/eu/cloudnetservice/plugins/simplenametags/minestom/MinestomSimpleNameTagsExtension.java
  plugins/simplenametags/src/main/java/eu/cloudnetservice/plugins/simplenametags/sponge/SpongeSimpleNameTagsPlugin.java
Labels: v: 4.X, in: node, t: fix, in: plugin, in: module, in: ext

#986 chore: remove gradle metadata as version catalogs are stable
  gradle/libs.versions.toml
Labels: v: 4.X, t: improvement

#1037 fix: register module updater before executing the module updates
  node/src/main/java/eu/cloudnetservice/node/Node.java
Labels: v: 4.X, in: node, t: fix
