Repository CloudNetService/CloudNet, pull requests merged in 2023-03, with the labels that each got.

#1149 fix: only construct one object mapper instance per jvm
  driver/src/main/java/eu/cloudnetservice/driver/inject/BootLayerConfigurator.java
  driver/src/main/java/eu/cloudnetservice/driver/inject/InjectionLayerProvider.java
  driver/src/main/java/eu/cloudnetservice/driver/network/rpc/defaults/object/ObjectMapperInjectRegistration.java
  driver/src/main/resources/META-INF/services/eu.cloudnetservice.driver.inject.BootLayerConfigurator
Labels: t: bug, p: high, v: 4.X, in: driver

#1151 [ci skip] fix: remove trailing space in crowdin configuration
  crowdin.yml
Labels: v: 4.X, t: fix

#1146 fix: properly close buffers to prevent memory leaks
  driver/src/main/java/eu/cloudnetservice/driver/network/buffer/DataBuf.java
  driver/src/main/java/eu/cloudnetservice/driver/network/chunk/defaults/DefaultFileChunkPacketSender.java
  driver/src/main/java/eu/cloudnetservice/driver/network/chunk/defaults/builder/DefaultChunkedPacketSenderBuilder.java
  driver/src/main/java/eu/cloudnetservice/driver/network/chunk/defaults/splitter/NetworkChannelsPacketSplitter.java
  driver/src/main/java/eu/cloudnetservice/driver/network/netty/NettyNetworkHandler.java
  driver/src/main/java/eu/cloudnetservice/driver/network/netty/buffer/NettyImmutableDataBuf.java
  driver/src/main/java/eu/cloudnetservice/driver/network/netty/buffer/NettyMutableDataBuf.java
  driver/src/main/java/eu/cloudnetservice/driver/network/protocol/PacketListenerRegistry.java
  driver/src/main/java/eu/cloudnetservice/driver/network/protocol/defaults/DefaultPacketListenerRegistry.java
  node/src/main/java/eu/cloudnetservice/node/cluster/sync/DefaultDataSyncRegistry.java
  node/src/main/java/eu/cloudnetservice/node/command/sub/ClusterCommand.java
  node/src/main/java/eu/cloudnetservice/node/network/listener/PacketServerChannelMessageListener.java
  node/src/main/java/eu/cloudnetservice/node/provider/NodeMessenger.java
  wrapper-jvm/src/main/java/eu/cloudnetservice/wrapper/network/listener/PacketAuthorizationResponseListener.java
  wrapper-jvm/src/main/java/eu/cloudnetservice/wrapper/network/listener/PacketServerChannelMessageListener.java
Labels: v: 4.X, t: fix

#1150 build: move fabric loader dependency to compile only scope
  modules/bridge/build.gradle.kts
Labels: v: 4.X, in: module

#1160 fix: correctly unregister services in bungeecord
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/bungeecord/BungeeCordBridgeManagement.java
Labels: v: 4.X, t: fix, in: module

#1163 fix: allow repetition of jvm options and command line arguments
  driver/src/main/java/eu/cloudnetservice/driver/service/ProcessConfiguration.java
Labels: v: 4.X, in: driver, t: fix

#1166 fix: added missing methods = "POST" in V2HttpHandlerService inside the Rest Module
  modules/rest/src/main/java/eu/cloudnetservice/modules/rest/v2/V2HttpHandlerService.java
Labels: v: 4.X, t: fix, in: module
