Repository CloudNetService/CloudNet, pull requests merged in 2023-05, with the labels that each got.

#1215 build: move checkstyle to version catalog
  build-extensions/src/main/kotlin/Versions.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: v: 4.X, t: dependencies

#1218 chore: update openapi specs due to recent ServiceConfiguration changes
  driver/src/main/java/eu/cloudnetservice/driver/service/ServiceCreateResult.java
  modules/rest/src/main/resources/documentation/swagger.json
Labels: v: 4.X, in: node, t: fix, in: module

#1220 chore: replace remaining gson usages outside the document package
  driver/src/main/java/eu/cloudnetservice/driver/module/DefaultModuleDependencyLoader.java
  driver/src/main/java/eu/cloudnetservice/driver/module/driver/DriverModule.java
  gradle/libs.versions.toml
  modules/cloudflare/src/main/java/eu/cloudnetservice/modules/cloudflare/cloudflare/CloudFlareRecordManager.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/_deprecated/NPCConstants.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/command/NPCCommand.java
  modules/report/src/main/java/eu/cloudnetservice/modules/report/config/PasteServer.java
  node/src/main/java/eu/cloudnetservice/node/console/animation/progressbar/ConsoleProgressWrappers.java
  node/src/main/java/eu/cloudnetservice/node/event/service/CloudServicePreLoadInclusionEvent.java
  node/src/main/java/eu/cloudnetservice/node/module/updater/ModuleUpdater.java
  node/src/main/java/eu/cloudnetservice/node/service/defaults/AbstractService.java
  node/src/main/java/eu/cloudnetservice/node/setup/DefaultConfigSetup.java
  node/src/main/java/eu/cloudnetservice/node/version/ServiceVersionProvider.java
  node/src/main/java/eu/cloudnetservice/node/version/execute/defaults/FabricApiVersionFetch.java
  node/src/main/java/eu/cloudnetservice/node/version/execute/defaults/PaperApiVersionFetchStepExecutor.java
  node/src/main/java/eu/cloudnetservice/node/version/execute/defaults/SpongeApiVersionFetchStepExecutor.java
Labels: v: 4.X, t: improvement

#1217 feat: warn about missing manifests and main classes
  node/src/main/java/eu/cloudnetservice/node/service/defaults/JVMService.java
Labels: v: 4.X, in: node, t: improvement

#1230 chore: improve the default signs layout
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/configuration/SignConfigurationEntry.java
Labels: v: 4.X, t: improvement, in: module

#1227 fix: reverse http handler calling order
  driver/src/main/java/eu/cloudnetservice/driver/network/netty/http/NettyHttpServerHandler.java
  driver/src/test/java/eu/cloudnetservice/driver/network/http/NettyHttpServerHttpTest.java
  modules/rest/src/main/java/eu/cloudnetservice/modules/rest/v2/V2HttpHandlerNode.java
Labels: v: 4.X, in: driver, t: fix, in: module

#1232 feat: enable injection of services from the service registry
  driver/src/main/java/eu/cloudnetservice/driver/registry/DefaultServiceRegistry.java
  driver/src/main/java/eu/cloudnetservice/driver/registry/injection/Service.java
  driver/src/test/java/eu/cloudnetservice/driver/registry/ServiceRegistryTest.java
Labels: v: 4.X, in: driver, t: improvement
