Repository CloudNetService/CloudNet, pull requests merged in 2023-10, with the labels that each got.

#1313 feat: support minecraft 1.20.2
  gradle/libs.versions.toml
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/bungeecord/BungeeCordPlayerManagementListener.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/fabric/FabricBridgeInitializer.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/fabric/FabricCustomPacketPayload.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/fabric/FabricDirectPlayerExecutor.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/fabric/mixin/forwarding/ClientIntentionPacketMixin.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/fabric/mixin/forwarding/ServerHandshakePacketListenerMixin.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/fabric/mixin/forwarding/ServerLoginPacketListenerMixin.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/fabric/mixin/handling/PlayerListMixin.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/listener/BukkitFunctionalityListener.java
  node/src/main/resources/files/velocity/velocity.toml
  node/src/main/resources/files/versions.json
Labels: v: 4.X, in: module

#1316 chore: update gradle to 8.4
  build-extensions/src/main/kotlin/extensions.kt
  build.gradle.kts
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/bukkit/BukkitBridgePlugin.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/bungeecord/BungeeCordBridgePlugin.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/fabric/FabricBridgeInitializer.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/minestom/MinestomBridgeExtension.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/nukkit/NukkitBridgePlugin.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/sponge/SpongeBridgePlugin.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/velocity/VelocityBridgePlugin.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/waterdog/WaterDogPEBridgePlugin.java
  modules/build.gradle.kts
  modules/cloudperms/src/main/java/eu/cloudnetservice/modules/cloudperms/bukkit/BukkitCloudPermissionsPlugin.java
  modules/cloudperms/src/main/java/eu/cloudnetservice/modules/cloudperms/bungee/BungeeCloudPermissionsPlugin.java
  modules/cloudperms/src/main/java/eu/cloudnetservice/modules/cloudperms/minestom/MinestomCloudPermissionsExtension.java
  modules/cloudperms/src/main/java/eu/cloudnetservice/modules/cloudperms/nukkit/NukkitCloudPermissionsPlugin.java
  modules/cloudperms/src/main/java/eu/cloudnetservice/modules/cloudperms/sponge/SpongeCloudPermissionsPlugin.java
  modules/cloudperms/src/main/java/eu/cloudnetservice/modules/cloudperms/velocity/VelocityCloudNetCloudPermissionsPlugin.java
  modules/cloudperms/src/main/java/eu/cloudnetservice/modules/cloudperms/waterdogpe/WaterdogPECloudPermissionsPlugin.java
  modules/labymod/src/main/java/eu/cloudnetservice/modules/labymod/platform/bungeecord/BungeeCordLabyModPlugin.java
  modules/labymod/src/main/java/eu/cloudnetservice/modules/labymod/platform/velocity/VelocityLabyModPlugin.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/BukkitNPCPlugin.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/bukkit/BukkitSignsPlugin.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/minestom/MinestomSignsExtension.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/nukkit/NukkitSignsPlugin.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/sponge/SpongeSignsPlugin.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/platform/bungee/BungeeCordSyncProxyPlugin.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/platform/velocity/VelocitySyncProxyPlugin.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/platform/waterdog/WaterDogPESyncProxyPlugin.java
  plugins/build.gradle.kts
  plugins/chat/src/main/java/eu/cloudnetservice/plugins/chat/BukkitChatPlugin.java
  plugins/chat/src/main/java/eu/cloudnetservice/plugins/chat/MinestomChatExtension.java
  plugins/chat/src/main/java/eu/cloudnetservice/plugins/chat/NukkitChatPlugin.java
  plugins/chat/src/main/java/eu/cloudnetservice/plugins/chat/SpongeChatPlugin.java
  plugins/papi-expansion/src/main/java/eu/cloudnetservice/plugins/papi/CloudNetPapiExpansion.java
  plugins/simplenametags/src/main/java/eu/cloudnetservice/plugins/simplenametags/bukkit/BukkitSimpleNameTagsPlugin.java
  plugins/simplenametags/src/main/java/eu/cloudnetservice/plugins/simplenametags/minestom/MinestomSimpleNameTagsExtension.java
  plugins/simplenametags/src/main/java/eu/cloudnetservice/plugins/simplenametags/sponge/SpongeSimpleNameTagsPlugin.java
Labels: v: 4.X, t: dependencies

#1318 chore: update all dependencies & actions
  .github/workflows/codeql-analysis.yml
  .github/workflows/gradle-release.yml
  .github/workflows/gradle.yml
  gradle/libs.versions.toml
  node/src/main/java/eu/cloudnetservice/node/command/defaults/DefaultCommandManager.java
Labels: v: 4.X, t: dependencies

#1315 fix: only start smart services on allowed nodes
  modules/smart/src/main/java/eu/cloudnetservice/modules/smart/listener/CloudNetTickListener.java
Labels: v: 4.X, t: fix, in: module

#1309 chore: update labymod module
  modules/labymod/src/main/java/eu/cloudnetservice/modules/labymod/config/LabyModConfiguration.java
  modules/labymod/src/main/java/eu/cloudnetservice/modules/labymod/config/LabyModDiscordRPC.java
  modules/labymod/src/main/java/eu/cloudnetservice/modules/labymod/config/LabyModPermissions.java
  modules/labymod/src/main/java/eu/cloudnetservice/modules/labymod/config/LabyModPlayerOptions.java
  modules/labymod/src/main/java/eu/cloudnetservice/modules/labymod/node/CloudNetLabyModModule.java
  modules/labymod/src/main/java/eu/cloudnetservice/modules/labymod/platform/PlatformLabyModListener.java
  modules/labymod/src/main/java/eu/cloudnetservice/modules/labymod/platform/PlatformLabyModManagement.java
Labels: v: 4.X, t: fix, in: module

#1225 fix: make sure to create parent directories in sftp
  modules/storage-s3/src/test/java/eu/cloudnetservice/modules/s3/S3TemplateStorageTest.java
  modules/storage-sftp/src/main/java/eu/cloudnetservice/modules/sftp/SFTPTemplateStorage.java
  modules/storage-sftp/src/test/java/eu/cloudnetservice/modules/sftp/SFTPTemplateStorageTest.java
  node/src/test/java/eu/cloudnetservice/node/template/LocalTemplateStorageTest.java
Labels: v: 4.X, t: fix, in: module

#1308 fix: check syncproxy perms after the player is accessible
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/bungeecord/BungeeCordPlayerManagementListener.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/bungeecord/PendingConnectionProxiedPlayer.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/platform/bungee/BungeeCordSyncProxyListener.java
Labels: v: 4.X, t: fix, in: module

#1322 fix: start service when exactly the max memory is used
  node/src/main/java/eu/cloudnetservice/node/service/defaults/AbstractService.java
Labels: v: 4.X, in: node, t: fix
