Repository CloudNetService/CloudNet, pull requests merged in 2023-04, with the labels that each got.

#1168 feat: support minecraft 1.19.4
  gradle/libs.versions.toml
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/fabric/FabricBridgeInitializer.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/fabric/FabricBridgeManagement.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/fabric/mixin/handling/MinecraftServerMixin.java
  node/src/main/resources/files/versions.json
Labels: v: 4.X, t: improvement, in: module

#1180 refactor: move cluster data classes out of network package
  driver/src/main/java/eu/cloudnetservice/driver/channel/ChannelMessageSender.java
  driver/src/main/java/eu/cloudnetservice/driver/cluster/NetworkCluster.java
  driver/src/main/java/eu/cloudnetservice/driver/cluster/NetworkClusterNode.java
  driver/src/main/java/eu/cloudnetservice/driver/cluster/NodeInfoSnapshot.java
  driver/src/main/java/eu/cloudnetservice/driver/provider/ClusterNodeProvider.java
  modules/influx/src/main/java/eu/cloudnetservice/modules/influx/publish/publishers/ConnectedNodeInfoPublisher.java
  modules/rest/src/main/java/eu/cloudnetservice/modules/rest/v2/V2HttpHandlerCluster.java
  node/src/main/java/eu/cloudnetservice/node/cluster/NodeServer.java
  node/src/main/java/eu/cloudnetservice/node/cluster/NodeServerProvider.java
  node/src/main/java/eu/cloudnetservice/node/cluster/defaults/DefaultLocalNodeServer.java
  node/src/main/java/eu/cloudnetservice/node/cluster/defaults/DefaultNodeServerProvider.java
  node/src/main/java/eu/cloudnetservice/node/cluster/defaults/RemoteNodeServer.java
  node/src/main/java/eu/cloudnetservice/node/command/sub/ClusterCommand.java
  node/src/main/java/eu/cloudnetservice/node/command/sub/TasksCommand.java
  node/src/main/java/eu/cloudnetservice/node/config/Configuration.java
  node/src/main/java/eu/cloudnetservice/node/config/JsonConfiguration.java
  node/src/main/java/eu/cloudnetservice/node/event/cluster/LocalNodeSnapshotConfigureEvent.java
  node/src/main/java/eu/cloudnetservice/node/event/cluster/NetworkClusterNodeInfoUpdateEvent.java
  node/src/main/java/eu/cloudnetservice/node/network/listener/PacketClientAuthorizationListener.java
  node/src/main/java/eu/cloudnetservice/node/network/listener/PacketClientServiceSyncAckListener.java
  node/src/main/java/eu/cloudnetservice/node/network/listener/message/NodeChannelMessageListener.java
  node/src/main/java/eu/cloudnetservice/node/network/packet/PacketServerServiceSyncAckPacket.java
  node/src/main/java/eu/cloudnetservice/node/provider/NodeClusterNodeProvider.java
  node/src/main/java/eu/cloudnetservice/node/setup/DefaultClusterSetup.java
  node/src/main/java/eu/cloudnetservice/node/setup/DefaultConfigSetup.java
Labels: v: 4.X, in: driver, t: improvement

#1181 fix: ignore http requests with an opaque uri
  driver/src/main/java/eu/cloudnetservice/driver/network/netty/http/NettyHttpServerHandler.java
Labels: v: 4.X, in: driver, t: fix

#1191 [ci skip] chore: update patch group name and disable netty updates
  .github/renovate.json
Labels: v: 4.X, t: ci

#1195 refactor: rewrite http tests & fix some smaller issues
  .github/workflows/gradle.yml
  driver/build.gradle.kts
  driver/src/main/java/eu/cloudnetservice/driver/network/netty/http/NettyHttpServerContext.java
  driver/src/test/java/eu/cloudnetservice/driver/network/NetworkTestCase.java
  driver/src/test/java/eu/cloudnetservice/driver/network/http/NettyHttpAnnotatedHandlerTest.java
  driver/src/test/java/eu/cloudnetservice/driver/network/http/NettyHttpServerHttpTest.java
  driver/src/test/java/eu/cloudnetservice/driver/network/http/NettyHttpServerTest.java
  driver/src/test/java/eu/cloudnetservice/driver/network/http/NettyHttpServerWebSocketTest.java
  driver/src/test/java/eu/cloudnetservice/driver/network/http/UriBuilder.java
  driver/src/test/java/eu/cloudnetservice/driver/network/http/WebSocketClientEndpoint.java
  driver/src/test/java/eu/cloudnetservice/driver/network/netty/communication/NettyNetworkServerClientTest.java
  gradle/libs.versions.toml
  modules/rest/src/main/java/eu/cloudnetservice/modules/rest/v2/V2HttpHandlerTemplateStorage.java
  node/src/main/java/eu/cloudnetservice/node/http/V2HttpHandler.java
Labels: v: 4.X, in: driver, t: refactor

#1197 fix: return empty document for non-existent file when parsing from path
  driver/src/main/java/eu/cloudnetservice/driver/document/DocumentFactory.java
  driver/src/main/java/eu/cloudnetservice/driver/document/gson/GsonDocumentFactory.java
  driver/src/test/java/eu/cloudnetservice/driver/document/DocumentSerialisationTest.java
Labels: v: 4.X, in: driver, t: fix, t: regression

#1202 update ProtocolLib download url
  cloudnet-modules/cloudnet-npcs/src/main/java/eu/cloudnetservice/cloudnet/ext/npcs/node/listener/IncludePluginListener.java
Labels: v: 3.X, t: fix, in: module

#1203 [ci skip] ci: make build action a requirement for merge group
  .github/workflows/gradle.yml
Labels: t: ci

#1200 fix: update ProtocolLib download url
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/node/NodeNPCManagement.java
Labels: v: 4.X, t: fix, in: module

#1209 fix: remove usages of checkerframework
  modules/cloudperms/src/main/java/eu/cloudnetservice/modules/cloudperms/sponge/service/CloudPermissionDescription.java
  modules/cloudperms/src/main/java/eu/cloudnetservice/modules/cloudperms/sponge/service/memory/InMemorySubjectData.java
Labels: v: 4.X, t: fix, in: module

#1213 chore(deps): bump minestom to 79ce9570ea
  gradle/libs.versions.toml
Labels: v: 4.X, t: dependencies

#1214 ci: update action configuration
  .github/workflows/codeql-analysis.yml
  .github/workflows/gradle-release.yml
  .github/workflows/gradle.yml
Labels: v: 4.X, t: ci
