Repository CloudNetService/CloudNet, pull requests merged in 2023-01, with the labels that each got.

#1041 fix: use correct database name for sign management
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/node/NodeSignManagement.java
Labels: p: high, v: 4.X, t: fix, in: module

#1038 chore: update for 1.19.3
  gradle/libs.versions.toml
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/fabric/FabricBridgeInitializer.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/entity/NPCBukkitPlatformSelector.java
  node/src/main/resources/files/versions.json
Labels: v: 4.X, in: node, t: improvement, in: module

#1065 chore: update for changes in aerogel
  driver/src/main/java/eu/cloudnetservice/driver/inject/DefaultInjectionLayer.java
  driver/src/main/java/eu/cloudnetservice/driver/inject/InjectUtil.java
Labels: v: 4.X, t: fix

#1066 fix: properly escape escaping chars in the mysql database
  modules/database-mongodb/src/test/java/eu/cloudnetservice/modules/mongodb/MongoDBDatabaseTest.java
  modules/database-mysql/src/main/java/eu/cloudnetservice/modules/mysql/MySQLDatabase.java
  modules/database-mysql/src/test/java/eu/cloudnetservice/modules/mysql/MySQLDatabaseTest.java
  node/src/test/java/eu/cloudnetservice/node/database/xodus/XodusDatabaseTest.java
Labels: v: 4.X, t: fix, in: module

#1058 fix: npc command editing profile resulting in an exception
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/command/NPCCommand.java
Labels: v: 4.X, t: fix, in: module

#1027 fix: make sure that we connect the player only to one service
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/bungeecord/BungeeCordDirectPlayerExecutor.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/velocity/VelocityDirectPlayerExecutor.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/waterdog/WaterDogPEDirectPlayerExecutor.java
Labels: v: 4.X, t: fix, in: module

#1030 fix: only stop a service if there are more than the minServiceCount
  modules/smart/src/main/java/eu/cloudnetservice/modules/smart/util/SmartUtil.java
Labels: v: 4.X, t: fix, in: module

#1017 fix: handle channel message queries that have no response correctly
  node/src/main/java/eu/cloudnetservice/node/network/listener/PacketServerChannelMessageListener.java
  wrapper-jvm/src/main/java/eu/cloudnetservice/wrapper/provider/WrapperMessenger.java
Labels: v: 4.X, in: node, t: fix, in: wrapper

#995 fix: make sure that permissions are removed after their lifetime
  driver/src/main/java/eu/cloudnetservice/driver/permission/AbstractPermissible.java
  driver/src/main/java/eu/cloudnetservice/driver/permission/Permissible.java
  node/src/main/java/eu/cloudnetservice/node/command/sub/PermissionsCommand.java
  node/src/main/java/eu/cloudnetservice/node/permission/DefaultDatabasePermissionManagement.java
Labels: v: 4.X, in: node, t: fix

#987 fix: make sure that all tablist placeholders are replaced correctly
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/platform/PlatformSyncProxyManagement.java
Labels: v: 4.X, t: fix, in: module

#1084 fix: make sure to load cloudperms before Vault
  modules/cloudperms/src/main/java/eu/cloudnetservice/modules/cloudperms/bukkit/BukkitCloudPermissionsPlugin.java
  modules/cloudperms/src/main/resources/plugin.minecraft_server.yml.template
Labels: v: 4.X, t: fix, in: module

#1087 fix: use concurrent queue for default installation setups
  node/src/main/java/eu/cloudnetservice/node/setup/DefaultInstallation.java
Labels: v: 4.X, in: node, t: fix

#958 chore: improve console tab suggestions
  gradle/libs.versions.toml
  node/build.gradle.kts
  node/src/main/java/eu/cloudnetservice/node/command/defaults/DefaultSuggestionProcessor.java
  node/src/main/java/eu/cloudnetservice/node/console/JLine3Completer.java
  node/src/main/java/eu/cloudnetservice/node/console/JLine3CompletionMatcher.java
  node/src/main/java/eu/cloudnetservice/node/console/JLine3Console.java
  node/src/test/java/eu/cloudnetservice/node/command/CommandProviderTest.java
Labels: v: 4.X, in: node, t: improvement

#1088 chore: bump checkstyle to 10.6.0
  build-extensions/src/main/kotlin/Versions.kt
Labels: v: 4.X, t: dependencies

#1080 fix: correct some netty channel options
  driver/src/main/java/eu/cloudnetservice/driver/network/netty/client/NettyNetworkClient.java
  driver/src/main/java/eu/cloudnetservice/driver/network/netty/http/NettyHttpServer.java
  driver/src/main/java/eu/cloudnetservice/driver/network/netty/server/NettyNetworkServer.java
Labels: v: 4.X, in: driver, t: improvement

#1040 chore: add file descriptor information to report output
  modules/report/src/main/java/eu/cloudnetservice/modules/report/emitter/defaults/SystemInfoDataEmitter.java
Labels: v: 4.X, t: improvement, in: module

#1031 chore: rename the event in the ModuleTask annotation to lifecycle
  driver/src/main/java/eu/cloudnetservice/driver/module/DefaultModuleWrapper.java
  driver/src/main/java/eu/cloudnetservice/driver/module/ModuleTask.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/node/CloudNetBridgeModule.java
  modules/cloudflare/src/main/java/eu/cloudnetservice/modules/cloudflare/CloudNetCloudflareModule.java
  modules/cloudperms/src/main/java/eu/cloudnetservice/modules/cloudperms/node/CloudNetCloudPermissionsModule.java
  modules/database-mongodb/src/main/java/eu/cloudnetservice/modules/mongodb/CloudNetMongoDatabaseModule.java
  modules/database-mysql/src/main/java/eu/cloudnetservice/modules/mysql/CloudNetMySQLDatabaseModule.java
  modules/dockerized-services/src/main/java/eu/cloudnetservice/modules/docker/DockerizedServicesModule.java
  modules/labymod/src/main/java/eu/cloudnetservice/modules/labymod/node/CloudNetLabyModModule.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/node/CloudNetNPCModule.java
  modules/report/src/main/java/eu/cloudnetservice/modules/report/CloudNetReportModule.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/node/CloudNetSignsModule.java
  modules/smart/src/main/java/eu/cloudnetservice/modules/smart/CloudNetSmartModule.java
  modules/storage-s3/src/main/java/eu/cloudnetservice/modules/s3/S3TemplateStorageModule.java
  modules/storage-sftp/src/main/java/eu/cloudnetservice/modules/sftp/SFTPTemplateStorageModule.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/node/CloudNetSyncProxyModule.java
Labels: v: 4.X, in: driver, t: improvement, in: module

#1032 feat: add includes & excludes to the service command
  node/src/main/java/eu/cloudnetservice/node/command/sub/ServiceCommand.java
Labels: v: 4.X, in: node, t: improvement

#1091 fix: add missing overrides for PlayerProvider methods on platforms
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/PlatformPlayerManager.java
Labels: v: 4.X, t: fix, in: module

#1097 chore: small improvement for platform inject annotation processing
  ext/platform-inject-support/processor/build.gradle.kts
  ext/platform-inject-support/processor/src/main/java/eu/cloudnetservice/ext/platforminject/processor/PlatformPluginProcessor.java
Labels: v: 4.X, t: improvement, in: ext

#1099 [ci skip] chore: rename the cloud service post construct listener
  node/src/main/java/eu/cloudnetservice/node/service/defaults/DefaultCloudServiceManager.java
Labels: v: 4.X, in: node, t: improvement

#1106 fix: don't use a client query parameter for ORDER BY field
  modules/database-mysql/src/main/java/eu/cloudnetservice/modules/mysql/MySQLDatabase.java
Labels: v: 4.X, t: fix, in: module

#1107 fix: register missing database provider rpc handler
  node/src/main/java/eu/cloudnetservice/node/Node.java
Labels: v: 4.X, in: node, t: fix
