Repository CloudNetService/CloudNet, pull requests merged in 2023-06, with the labels that each got.

#1234 chore: replace service registry usages
  driver/src/main/java/eu/cloudnetservice/driver/registry/ServiceRegistry.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/node/command/PlayersCommand.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/player/CloudPlayer.java
  modules/labymod/src/main/java/eu/cloudnetservice/modules/labymod/platform/PlatformLabyModManagement.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/node/CloudNetNPCModule.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/node/NPCCommand.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/BukkitPlatformNPCManagement.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/entity/BukkitPlatformSelectorEntity.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/entity/EntityBukkitPlatformSelectorEntity.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/entity/NPCBukkitPlatformSelector.java
  modules/report/src/main/java/eu/cloudnetservice/modules/report/CloudNetReportModule.java
  modules/report/src/main/java/eu/cloudnetservice/modules/report/command/ReportCommand.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/node/CloudNetSignsModule.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/PlatformSign.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/bukkit/BukkitPlatformSign.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/bukkit/BukkitSignManagement.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/minestom/MinestomPlatformSign.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/minestom/MinestomSignManagement.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/nukkit/NukkitPlatformSign.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/nukkit/NukkitSignManagement.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/sponge/SpongePlatformSign.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/sponge/SpongeSignManagement.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/node/CloudNetSyncProxyModule.java
  node/src/main/java/eu/cloudnetservice/node/Node.java
Labels: v: 4.X, in: node, in: driver, t: improvement, in: module

#1248 build: add md5 snapshots repo to make cloudnet compile again
  ext/platform-inject-support/runtime/build.gradle.kts
  modules/build.gradle.kts
Labels: v: 4.X, t: fix

#1250 fix: update waterdog repository
  ext/platform-inject-support/runtime/build.gradle.kts
  modules/build.gradle.kts
Labels: v: 4.X, t: fix

#1256 fix: do not set ssl explicitly to false and use mariadb 11.1.1-rc in tests
  modules/database-mysql/src/main/java/eu/cloudnetservice/modules/mysql/CloudNetMySQLDatabaseModule.java
  modules/database-mysql/src/main/java/eu/cloudnetservice/modules/mysql/MySQLDatabaseProvider.java
  modules/database-mysql/src/main/java/eu/cloudnetservice/modules/mysql/config/MySQLConnectionEndpoint.java
  modules/database-mysql/src/test/java/eu/cloudnetservice/modules/mysql/MySQLDatabaseTest.java
Labels: v: 4.X, t: fix, in: module

#1257 chore: bump npc lib to beta5, fix some smaller npc issues observed during testing
  gradle/libs.versions.toml
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/entity/NPCBukkitPlatformSelector.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/listener/BukkitFunctionalityListener.java
Labels: v: 4.X, t: fix, in: module, t: dependencies

#1255 fix: spawn all npcs in already loaded chunks on start
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/BukkitPlatformNPCManagement.java
Labels: v: 4.X, t: fix, in: module

#1249 fix: set the floating item to null if the material is air
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/command/NPCCommand.java
Labels: v: 3.X, t: fix, in: module

#1252 feat: support minecraft 1.20
  gradle/libs.versions.toml
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/fabric/FabricBridgeInitializer.java
  node/src/main/resources/files/versions.json
Labels: v: 4.X, in: node, t: improvement

#1262 fix: draining causes jvm halt instead of a stop
  node/src/main/java/eu/cloudnetservice/node/Node.java
  node/src/main/java/eu/cloudnetservice/node/ShutdownHandler.java
  node/src/main/java/eu/cloudnetservice/node/TickLoop.java
  node/src/main/java/eu/cloudnetservice/node/cluster/defaults/DefaultLocalNodeServer.java
  node/src/main/java/eu/cloudnetservice/node/command/sub/ClusterCommand.java
Labels: v: 4.X, in: node, t: fix
