Repository CloudNetService/CloudNet, pull requests merged in 2024-06, with the labels that each got.

#1417 feat: add serializers for java.time classes to gson
  driver/src/main/java/eu/cloudnetservice/driver/document/gson/DurationTypeAdapter.java
  driver/src/main/java/eu/cloudnetservice/driver/document/gson/GsonProvider.java
  driver/src/main/java/eu/cloudnetservice/driver/document/gson/TimeTypeAdapter.java
  driver/src/test/java/eu/cloudnetservice/driver/document/gson/JavaTimeSerializerTest.java
Labels: v: 4.X, in: driver, t: improvement

#1418 feat: ignore unloaded chunks when choosing a free sign
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/PlatformSignManagement.java
Labels: v: 4.X, t: improvement, in: module

#1421 chore: remove the rest configuration and unused web listeners
  node/src/main/java/eu/cloudnetservice/node/config/Configuration.java
  node/src/main/java/eu/cloudnetservice/node/config/JsonConfiguration.java
  node/src/main/java/eu/cloudnetservice/node/config/RestConfiguration.java
  node/src/main/java/eu/cloudnetservice/node/setup/DefaultConfigSetup.java
Labels: v: 4.X, in: node

#1423 feat: improve code style config to ensure no blank lines before rbrace
  .idea/codeStyles/Project.xml
Labels: v: 4.X

#1425 fix: ignore fabric fake players when getting player information
  checkstyle.xml
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/fabric/FabricBridgeManagement.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/fabric/FabricDirectPlayerExecutor.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/fabric/access/CustomPayloadAccessor.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/fabric/mixin/forwarding/ClientIntentionPacketMixin.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/fabric/mixin/forwarding/CompressionThresholdMixin.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/fabric/mixin/forwarding/ConnectionMixin.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/fabric/mixin/forwarding/ServerHandshakePacketListenerMixin.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/fabric/mixin/forwarding/ServerLoginPacketListenerMixin.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/fabric/mixin/handling/MinecraftServerMixin.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/fabric/mixin/handling/PlayerListMixin.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/fabric/mixin/payload/CustomPayloadMixin.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/fabric/util/BridgedClientConnection.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/fabric/util/BridgedServer.java
  modules/bridge/src/main/resources/cloudnet_bridge.accesswidener
  modules/bridge/src/main/resources/cloudnet_bridge.mixins.json
Labels: v: 4.X, in: module
