Repository CloudNetService/CloudNet, pull requests merged in 2024-08, with the labels that each got.

#1476 chore: update the shadow plugin and use the new group id
  gradle/libs.versions.toml
Labels: v: 4.X, t: fix

#1413 feat: toggle for remote inclusion caches
  driver/src/main/java/eu/cloudnetservice/driver/service/ServiceRemoteInclusion.java
  node/src/main/java/eu/cloudnetservice/node/command/sub/GroupsCommand.java
  node/src/main/java/eu/cloudnetservice/node/command/sub/TasksCommand.java
  node/src/main/java/eu/cloudnetservice/node/event/service/CloudServicePreLoadInclusionEvent.java
  node/src/main/java/eu/cloudnetservice/node/provider/NodeGroupConfigurationProvider.java
  node/src/main/java/eu/cloudnetservice/node/provider/NodeServiceTaskProvider.java
  node/src/main/java/eu/cloudnetservice/node/service/defaults/AbstractService.java
  node/src/main/resources/lang/en_US.properties
Labels: v: 4.X, in: node, t: improvement

#1474 chore: update GitHub actions
  .github/workflows/codeql-analysis.yml
  .github/workflows/gradle-release.yml
  .github/workflows/gradle.yml
  .github/workflows/prbranch.yml
Labels: t: fix, t: improvement, t: ci

#1478 fix: ensure to only remove npcs that are currently spawned
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/entity/EntityBukkitPlatformSelectorEntity.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/entity/NPCBukkitPlatformSelector.java
Labels: v: 4.X, t: fix, in: module

#1484 fix: correcly relocate npclib to ensure adventure compability
  gradle/libs.versions.toml
  modules/build.gradle.kts
  modules/npcs/build.gradle.kts
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/BukkitPlatformNPCManagement.java
Labels: v: 4.X, in: module, t: dependencies

#1486 fix: schedule no tasks when signs are disabled
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/bukkit/BukkitSignManagement.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/nukkit/NukkitSignManagement.java
Labels: v: 4.X, t: fix, in: module

#1491 chore: replace deprecated converterClass property in logback config
  node/src/main/resources/logback.xml
Labels: v: 4.X, in: node, t: fix

#1492 fix: testcontainers related test issues
  driver/src/test/resources/logback-test.xml
  modules/database-mongodb/src/test/resources/logback-test.xml
  modules/database-mysql/src/test/java/eu/cloudnetservice/modules/mysql/MySQLDatabaseTest.java
  modules/database-mysql/src/test/resources/logback-test.xml
  modules/report/src/test/resources/logback-test.xml
  modules/storage-s3/src/test/resources/logback-test.xml
  modules/storage-sftp/src/test/resources/logback-test.xml
  modules/syncproxy/src/test/resources/logback-test.xml
  node/src/test/resources/logback-test.xml
Labels: v: 4.X, t: fix

#1490 refactor: improve service process output reading
  checkstyle.xml
  modules/dockerized-services/src/main/java/eu/cloudnetservice/modules/docker/DockerizedService.java
  modules/dockerized-services/src/main/java/eu/cloudnetservice/modules/docker/DockerizedServiceLogCache.java
  node/src/main/java/eu/cloudnetservice/node/service/ServiceConsoleLogCache.java
  node/src/main/java/eu/cloudnetservice/node/service/defaults/AbstractService.java
  node/src/main/java/eu/cloudnetservice/node/service/defaults/DefaultCloudServiceManager.java
  node/src/main/java/eu/cloudnetservice/node/service/defaults/JVMService.java
  node/src/main/java/eu/cloudnetservice/node/service/defaults/log/AbstractServiceLogCache.java
  node/src/main/java/eu/cloudnetservice/node/service/defaults/log/ProcessServiceLogCache.java
Labels: v: 4.X, in: node, t: improvement
