Repository CloudNetService/CloudNet, pull requests merged in 2024-07, with the labels that each got.

#1427 chore: disable some renovate updates
  .github/renovate.json
Labels: v: 4.X, t: improvement

#1428 chore: replace deprecated wrapper validation action
  .github/workflows/gradle-release.yml
  .github/workflows/gradle.yml
Labels: v: 4.X, t: ci

#1430 [ci skip] fix: remove wrong colon on docker image update deactivation
  .github/renovate.json
Labels: v: 4.X, t: fix

#1431 feat: support minecraft 1.21
  gradle/libs.versions.toml
  modules/bridge/build.gradle.kts
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/fabric/FabricBridgeInitializer.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/fabric/FabricDirectPlayerExecutor.java
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/platform/sponge/SpongeBridgePlugin.java
  modules/npcs/build.gradle.kts
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/command/NPCCommand.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/entity/EntityBukkitPlatformSelectorEntity.java
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/util/ReflectionUtil.java
  modules/signs/build.gradle.kts
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/PlatformSign.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/bukkit/BukkitPlatformSign.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/bukkit/BukkitSignManagement.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/minestom/MinestomPlatformSign.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/minestom/MinestomSignManagement.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/nukkit/NukkitPlatformSign.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/nukkit/NukkitSignManagement.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/sponge/SpongePlatformSign.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/sponge/SpongeSignManagement.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/sponge/SpongeSignsPlugin.java
  node/src/main/java/eu/cloudnetservice/node/version/execute/defaults/SpongeApiVersionFetchStepExecutor.java
  node/src/main/resources/files/versions.json
  plugins/luckperms/src/main/java/eu/cloudnetservice/plugins/luckperms/SpongeLuckPermsPlugin.java
Labels: v: 4.X, in: node, in: module

#1432 chore: use classdesc instead of asm type
  modules/report/src/main/java/eu/cloudnetservice/modules/report/emitter/defaults/HeapDumpDataEmitter.java
Labels: v: 4.X

#1437 chore: add java version constants for java 22-24
  common/src/main/java/eu/cloudnetservice/common/jvm/JavaVersion.java
Labels: v: 4.X, in: common

#1439 chore: replace old jansi dependency
  gradle/libs.versions.toml
  node/src/main/java/eu/cloudnetservice/node/console/ConsoleColor.java
  node/src/main/java/eu/cloudnetservice/node/console/JLine3Console.java
  node/src/main/java/eu/cloudnetservice/node/console/animation/AbstractConsoleAnimation.java
  node/src/main/java/eu/cloudnetservice/node/console/animation/setup/ConsoleSetupAnimation.java
Labels: v: 4.X, in: node

#1452 fix: remove explicit opcode checking for LDC instruction
  wrapper-jvm/src/main/java/eu/cloudnetservice/wrapper/transform/bukkit/BukkitJavaVersionCheckTransformer.java
Labels: v: 4.X, t: fix, in: wrapper

#1448 chore: add missing nullability annotations for toString and equals
  driver/src/main/java/eu/cloudnetservice/driver/CloudNetVersion.java
  driver/src/main/java/eu/cloudnetservice/driver/command/CommandInfo.java
  driver/src/main/java/eu/cloudnetservice/driver/module/ModuleDependency.java
  driver/src/main/java/eu/cloudnetservice/driver/service/ServiceId.java
  launcher/java22/src/main/java/eu/cloudnetservice/launcher/java22/dependency/Dependency.java
  modules/syncproxy/src/main/java/eu/cloudnetservice/modules/syncproxy/config/SyncProxyLoginConfiguration.java
  node/src/main/java/eu/cloudnetservice/node/command/source/DriverCommandSource.java
Labels: v: 4.X, t: improvement

#1455 chore: update npc-lib to 3.0.0-beta7
  gradle/libs.versions.toml
  modules/npcs/build.gradle.kts
Labels: v: 4.X, in: module, t: dependencies

#1451 chore: remove the hostname question in the task setup
  node/src/main/java/eu/cloudnetservice/node/setup/SpecificTaskSetup.java
Labels: v: 4.X, t: fix

#1460 fix: npc command does not set showfullservices correctly
  modules/npcs/src/main/java/eu/cloudnetservice/modules/npc/platform/bukkit/command/NPCCommand.java
Labels: v: 4.X, t: fix, in: module

#1461 fix: prevent blocking operations on the netty event loop
  driver/src/main/java/eu/cloudnetservice/driver/network/netty/NettyNetworkChannel.java
  driver/src/main/java/eu/cloudnetservice/driver/network/netty/NettyUtil.java
  driver/src/main/java/eu/cloudnetservice/driver/network/netty/client/NettyNetworkClient.java
  driver/src/main/java/eu/cloudnetservice/driver/network/netty/server/NettyNetworkServer.java
  driver/src/main/java/eu/cloudnetservice/driver/network/protocol/PacketSender.java
  driver/src/main/java/eu/cloudnetservice/driver/network/scheduler/FallbackRejectionHandler.java
  driver/src/main/java/eu/cloudnetservice/driver/network/scheduler/NetworkTaskScheduler.java
  driver/src/main/java/eu/cloudnetservice/driver/network/scheduler/ScalingNetworkTaskScheduler.java
  driver/src/main/java/eu/cloudnetservice/driver/network/scheduler/TaskSchedulingAction.java
  driver/src/main/java/eu/cloudnetservice/driver/network/scheduler/TimedSynchronousQueue.java
  driver/src/test/java/eu/cloudnetservice/driver/network/netty/NettyUtilTest.java
  driver/src/test/java/eu/cloudnetservice/driver/network/scheduler/ScalingNetworkTaskSchedulerTest.java
Labels: p: high, v: 4.X, in: driver, t: fix

#1464 drop: packet receive and packet send event
  driver/src/main/java/eu/cloudnetservice/driver/event/events/network/NetworkChannelPacketReceiveEvent.java
  driver/src/main/java/eu/cloudnetservice/driver/event/events/network/NetworkChannelPacketSendEvent.java
  driver/src/main/java/eu/cloudnetservice/driver/network/netty/NettyNetworkChannel.java
  driver/src/main/java/eu/cloudnetservice/driver/network/netty/NettyNetworkHandler.java
  driver/src/main/java/eu/cloudnetservice/driver/network/netty/client/NettyNetworkClient.java
  driver/src/main/java/eu/cloudnetservice/driver/network/netty/client/NettyNetworkClientHandler.java
  driver/src/main/java/eu/cloudnetservice/driver/network/netty/client/NettyNetworkClientInitializer.java
  driver/src/main/java/eu/cloudnetservice/driver/network/netty/server/NettyNetworkServer.java
  driver/src/main/java/eu/cloudnetservice/driver/network/netty/server/NettyNetworkServerHandler.java
  driver/src/main/java/eu/cloudnetservice/driver/network/netty/server/NettyNetworkServerInitializer.java
  driver/src/test/java/eu/cloudnetservice/driver/network/netty/communication/NettyNetworkServerClientTest.java
  node/src/main/java/eu/cloudnetservice/node/boot/BootFactories.java
  node/src/main/java/eu/cloudnetservice/node/network/DefaultNetworkClientChannelHandler.java
  node/src/main/java/eu/cloudnetservice/node/network/DefaultNetworkServerChannelHandler.java
  wrapper-jvm/src/main/java/eu/cloudnetservice/wrapper/inject/BootFactories.java
  wrapper-jvm/src/main/java/eu/cloudnetservice/wrapper/network/NetworkClientChannelHandler.java
Labels: v: 4.X, in: driver, a: api
