Repository CloudNetService/CloudNet, pull requests merged in 2024-03, with the labels that each got.

#1358 chore: update all dependencies
  build.gradle.kts
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: v: 4.X, t: dependencies

#1360 fix: update sshj to 0.38.0 and fix heartbeat issue
  gradle/libs.versions.toml
  modules/storage-sftp/src/main/java/eu/cloudnetservice/modules/sftp/sshj/ActiveHeartbeatKeepAliveProvider.java
Labels: v: 4.X, t: fix, in: module, t: dependencies

#1361 chore: update remaining deps
  gradle/libs.versions.toml
  modules/database-mysql/src/test/java/eu/cloudnetservice/modules/mysql/MySQLDatabaseTest.java
Labels: v: 4.X, t: dependencies

#1371 feat: ignore non-existent worlds when choosing a free sign
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/PlatformSignManagement.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/bukkit/functionality/SignsCommand.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/minestom/functionality/SignsCommand.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/nukkit/functionality/SignsCommand.java
  modules/signs/src/main/java/eu/cloudnetservice/modules/signs/platform/sponge/functionality/SignsCommand.java
Labels: v: 4.X, t: improvement, in: module

#1374 fix: make the player kick command reason quoted to allow flags
  modules/bridge/src/main/java/eu/cloudnetservice/modules/bridge/node/command/PlayersCommand.java
Labels: v: 4.X, t: fix, in: module

#1379 build: ensure :processResources runs before :compileJava
  build.gradle.kts
Labels: p: high, v: 4.X, t: fix, in: module
