Repository CloudNetService/CloudNet, pull requests merged in 2025-05, with the labels that each got.

#1615 feat: minecraft 1.21.5
  gradle/libs.versions.toml
  modules/bridge/impl/src/main/java/eu/cloudnetservice/modules/bridge/impl/platform/fabric/mixin/handling/MinecraftServerMixin.java
  modules/npcs/impl/src/main/java/eu/cloudnetservice/modules/npc/impl/node/NodeNPCManagement.java
  modules/signs/impl/src/main/java/eu/cloudnetservice/modules/signs/impl/platform/minestom/MinestomSignBlockHandler.java
  node/impl/src/main/resources/files/versions.json
Labels: v: 4.X, in: node, in: module

#1616 fix: properly read docker task config from service props & task props
  modules/dockerized-services/impl/src/main/java/eu/cloudnetservice/modules/docker/impl/DockerizedLocalCloudServiceFactory.java
  modules/dockerized-services/impl/src/main/java/eu/cloudnetservice/modules/docker/impl/DockerizedService.java
Labels: v: 4.X, t: fix, in: module

#1621 fix: dockerized-services module image handling
  modules/dockerized-services/api/src/main/java/eu/cloudnetservice/modules/docker/config/DockerImage.java
  modules/dockerized-services/api/src/test/java/eu/cloudnetservice/modules/docker/config/DockerImageTest.java
  modules/dockerized-services/impl/src/main/java/eu/cloudnetservice/modules/docker/impl/DockerizedService.java
Labels: v: 4.X, t: fix, in: module

#1485 feat: add npc info command
  modules/npcs/impl/src/main/java/eu/cloudnetservice/modules/npc/impl/platform/bukkit/command/NPCCommand.java
Labels: v: 4.X, t: improvement, in: module

#1625 chore: update packet events to 2.8.0
  gradle/libs.versions.toml
  modules/npcs/impl/src/main/java/eu/cloudnetservice/modules/npc/impl/node/NodeNPCManagement.java
Labels: v: 4.X, in: module

#1627 ci: let explicit workflow dispatch also publish launcher metadata
  .github/workflows/gradle.yml
Labels: v: 4.X, t: ci

#1628 Add service uuid to LuckPerms context
  plugins/luckperms/src/main/java/eu/cloudnetservice/plugins/luckperms/CloudNetContextCalculator.java
Labels: v: 4.X, t: improvement, in: plugin

#1630 ci: fine-tune the build action a bit
  .github/workflows/gradle.yml
Labels: v: 4.X, t: ci

#1635 chore: update CloudNet-Rest to 0.2.0
  modules.json
Labels: v: 4.X

#1637 build: replace publishing to ossrh with central portal
  .github/workflows/gradle-release.yml
  .github/workflows/gradle.yml
  README.md
  build.gradle.kts
Labels: v: 4.X, t: ci
